import { useQuery } from "@tanstack/react-query";
import { FEED_SELECT, normalizePost } from "@/features/feed/api";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/providers/AuthProvider";

const usePostList = (table: "bookmarks" | "reactions", type?: string) => {
  const { user } = useAuth();
  return useQuery({ queryKey: ["activity", table, type, user?.id], enabled: !!user, queryFn: async () => { let query: any = supabase.from(table).select(`post:posts!${table}_post_id_fkey(${FEED_SELECT})`).eq("user_id", user!.id).order("created_at", { ascending: false }); if (type) query = query.eq("type", type).eq("target_type", "post").is("acted_as_page_id", null); const { data, error } = await query; if (error) throw error; return (data ?? []).map((row: any) => row.post).filter(Boolean).map((post: any) => normalizePost(post)); } });
};
export const useSavedPosts = () => usePostList("bookmarks");
export const useLikedPosts = () => usePostList("reactions", "like");
export function useSavedProjects() { const { user } = useAuth(); return useQuery({ queryKey: ["activity-saved-projects", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("saved_projects").select("project:projects!saved_projects_project_id_fkey(*)").eq("user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return (data ?? []).map((row: any) => row.project).filter(Boolean); } }); }
export function useLikedProjects() { const { user } = useAuth(); return useQuery({ queryKey: ["activity-liked-projects", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("reactions").select("project:projects!reactions_project_id_fkey(*)").eq("user_id", user!.id).eq("type", "like").eq("target_type", "project").is("acted_as_page_id", null).order("created_at", { ascending: false }); if (error) throw error; return (data ?? []).map((row: any) => row.project).filter(Boolean); } }); }
export function useDraftPosts(status: "draft" | "scheduled") { const { user } = useAuth(); return useQuery({ queryKey: ["activity-posts", status, user?.id], enabled: !!user, queryFn: async () => { let query = supabase.from("posts").select(FEED_SELECT).eq("author_id", user!.id).eq("status", status).eq("is_deleted", false); query = status === "scheduled" ? query.order("scheduled_for", { ascending: true }) : query.order("created_at", { ascending: false }); const { data, error } = await query; if (error) throw error; return (data ?? []).map((post: any) => normalizePost(post)); } }); }
export function useViewHistory() { const { user } = useAuth(); return useQuery({ queryKey: ["activity-history", user?.id], enabled: !!user, queryFn: async () => { const [posts, projects] = await Promise.all([supabase.from("post_views").select(`viewed_at, post:posts!post_views_post_id_fkey(${FEED_SELECT})`).eq("user_id", user!.id).order("viewed_at", { ascending: false }).limit(50), supabase.from("project_views").select("viewed_at, project:projects!project_views_project_id_fkey(*)").eq("user_id", user!.id).order("viewed_at", { ascending: false }).limit(50)]); if (posts.error) throw posts.error; if (projects.error) throw projects.error; return [...(posts.data ?? []).filter((row: any) => row.post).map((row: any) => ({ kind: "post", viewedAt: row.viewed_at, value: normalizePost(row.post) })), ...(projects.data ?? []).filter((row: any) => row.project).map((row: any) => ({ kind: "project", viewedAt: row.viewed_at, value: row.project }))].sort((a, b) => new Date(b.viewedAt).getTime() - new Date(a.viewedAt).getTime()); } }); }
export function useAffiliateProjects() { const { user } = useAuth(); return useQuery({ queryKey: ["activity-affiliates", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("affiliate_relationships").select("*, project:projects(id, title, thumbnail_url, price_usd, promo_price_usd, slug)").eq("affiliate_user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } }); }
export function useAffiliateDashboard(relationshipId: string | undefined) { return useQuery({ queryKey: ["affiliate-dashboard", relationshipId], enabled: !!relationshipId, queryFn: async () => { const { data, error } = await supabase.rpc("get_affiliate_dashboard", { p_relationship_id: relationshipId }); if (error) throw error; return data; }, staleTime: 15000 }); }
export function useEventsActivity() { const { user } = useAuth(); return useQuery({ queryKey: ["activity-events", user?.id], enabled: !!user, queryFn: async () => { const [tickets, purchases, rooms] = await Promise.all([supabase.from("event_tickets").select("project:projects!event_tickets_project_id_fkey(id, title, thumbnail_url, project_event_details(event_date))").eq("buyer_id", user!.id), supabase.from("purchases").select("project:projects!purchases_project_id_fkey(id, title, thumbnail_url, project_type, project_meeting_details(scheduled_at))").eq("buyer_id", user!.id), supabase.from("room_meetings").select("id, scheduled_at, project:projects!room_meetings_project_id_fkey(id, title, thumbnail_url), room_members!inner(user_id)").eq("room_members.user_id", user!.id)]); if (tickets.error) throw tickets.error; if (purchases.error) throw purchases.error; if (rooms.error) throw rooms.error; const events = (tickets.data ?? []).map((row: any) => row.project && ({ kind: "Event", ...row.project, when: row.project.project_event_details?.[0]?.event_date ?? null })).filter(Boolean); const meetings = (purchases.data ?? []).filter((row: any) => row.project?.project_type === "meeting").map((row: any) => ({ kind: "Meeting", ...row.project, when: row.project.project_meeting_details?.[0]?.scheduled_at ?? null })); const roomMeetings = (rooms.data ?? []).map((row: any) => row.project && ({ kind: "Room meeting", ...row.project, when: row.scheduled_at })).filter(Boolean); return [...events, ...meetings, ...roomMeetings].sort((a: any, b: any) => (a.when ?? "9999").localeCompare(b.when ?? "9999")); } }); }
