import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/providers/AuthProvider";

export type Interest = { id: string; category_id: string | null; name: string; is_active: boolean };
export type Category = { id: string; name: string; sort_order: number; interests: Interest[] };
export type Recommendation = { id: string; username: string; display_name: string; avatar_url: string | null; bio: string | null; follower_count: number; shared_interest_count: number; is_admin_suggested: boolean };

export function useOnboardingStatus() { const { user } = useAuth(); return useQuery({ queryKey:["onboarding-status",user?.id], enabled:!!user, staleTime:30_000, queryFn:async()=>{const [{data:profile,error:profileError},{data:interest,error:interestError}]=await Promise.all([supabase.from("profiles").select("onboarding_completed").eq("id",user!.id).single(),supabase.from("user_interests").select("user_id").eq("user_id",user!.id).limit(1).maybeSingle()]);if(profileError)throw profileError;if(interestError)throw interestError;return{completed:!!profile.onboarding_completed,hasInterests:!!interest};}}); }
export function useCategories(){return useQuery({queryKey:["categories-with-interests"],staleTime:5*60_000,queryFn:async():Promise<Category[]>=>{const [{data:categories,error:catError},{data:interests,error:intError}]=await Promise.all([supabase.from("categories").select("id, name, sort_order").eq("is_active",true).order("sort_order"),supabase.from("interests").select("id, category_id, name, is_active").eq("is_active",true)]);if(catError)throw catError;if(intError)throw intError;return(categories??[]).map(category=>({...category,interests:(interests??[]).filter(interest=>interest.category_id===category.id)}));}});}
export function useMyInterests(){const{user}=useAuth();return useQuery({queryKey:["my-interest-ids",user?.id],enabled:!!user,queryFn:async()=>{const{data,error}=await supabase.from("user_interests").select("interest_id").eq("user_id",user!.id);if(error)throw error;return(data??[]).map(row=>row.interest_id);}});}
export function useSaveInterests(){const{user}=useAuth();const client=useQueryClient();return useMutation({mutationFn:async(ids:string[])=>{if(!user)throw new Error("Not signed in");const{data,error}=await supabase.from("user_interests").select("interest_id").eq("user_id",user.id);if(error)throw error;const current=new Set((data??[]).map(row=>row.interest_id));const next=new Set(ids);const add=ids.filter(id=>!current.has(id));const remove=[...current].filter(id=>!next.has(id));if(add.length){const{error:addError}=await supabase.from("user_interests").insert(add.map(interest_id=>({user_id:user.id,interest_id})));if(addError&&addError.code!=="23505")throw addError;}if(remove.length){const{error:removeError}=await supabase.from("user_interests").delete().eq("user_id",user.id).in("interest_id",remove);if(removeError)throw removeError;}},onSuccess:()=>{void client.invalidateQueries({queryKey:["onboarding-status",user?.id]});void client.invalidateQueries({queryKey:["my-interest-ids",user?.id]});}});}
export function useRecommendations(){const{user}=useAuth();return useQuery({queryKey:["onboarding-recommendations",user?.id],enabled:!!user,staleTime:Infinity,queryFn:async():Promise<Recommendation[]>=>{const{data,error}=await supabase.rpc("get_onboarding_recommendations",{p_limit:5});if(error)throw error;return data??[];}});}
export function useFollow(personId:string){const{user}=useAuth();const client=useQueryClient();return useMutation({mutationFn:async(following:boolean)=>{if(!user)throw new Error("Not signed in");const query=supabase.from("follows");const{error}=following?await query.delete().eq("follower_id",user.id).eq("following_id",personId):await query.insert({follower_id:user.id,following_id:personId});if(error)throw error;},onSuccess:()=>void client.invalidateQueries({queryKey:["onboarding-follow",personId,user?.id]})});}
export function useIsFollowing(personId:string){const{user}=useAuth();return useQuery({queryKey:["onboarding-follow",personId,user?.id],enabled:!!user,queryFn:async()=>{const{data,error}=await supabase.from("follows").select("follower_id").eq("follower_id",user!.id).eq("following_id",personId).maybeSingle();if(error)throw error;return!!data;}});}
export function useCompleteOnboarding(){const{user,refreshProfile}=useAuth();const client=useQueryClient();return useMutation({mutationFn:async()=>{if(!user)throw new Error("Not signed in");const{error}=await supabase.from("profiles").update({onboarding_completed:true}).eq("id",user.id);if(error)throw error;await refreshProfile();},onSuccess:()=>void client.invalidateQueries({queryKey:["onboarding-status",user?.id]})});}
