import { useMemo, useState } from "react";
import { View } from "react-native";
import { useRouter } from "expo-router";
import { Button, Chip, Input, Screen, Section, Text } from "@/components/core";
import { ErrorState, Skeleton } from "@/components/feedback";
import { friendlyAuthError } from "@/features/auth/validation";
import { useCategories, useMyInterests, useSaveInterests } from "@/features/onboarding/api";
const MIN_INTERESTS=3;
export default function Interests(){const router=useRouter();const categories=useCategories();const mine=useMyInterests();const save=useSaveInterests();const [selectionOverride,setSelectionOverride]=useState<Set<string>|null>(null);const selected=selectionOverride??new Set(mine.data??[]);const [query,setQuery]=useState("");const [error,setError]=useState<string|null>(null);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return(categories.data??[]).map(category=>({...category,interests:category.interests.filter(interest=>!q||interest.name.toLowerCase().includes(q))})).filter(category=>category.interests.length);},[categories.data,query]);const toggle=(id:string)=>setSelectionOverride(()=>{const next=new Set(selected);if(next.has(id))next.delete(id);else next.add(id);return next;});const submit=async()=>{if(selected.size<MIN_INTERESTS)return;setError(null);try{await save.mutateAsync([...selected]);router.push("/(onboarding)/people");}catch(err){setError(friendlyAuthError(err,"Couldn’t save your interests. Check your connection and try again."));}};if(categories.isError||mine.isError)return <Screen><ErrorState message="Couldn’t load topics. Check your connection and try again." onRetry={()=>{void categories.refetch();void mine.refetch();}}/></Screen>;return <Screen><Text variant="caption" color="accent">STEP 1 OF 2</Text><Text variant="title" style={{marginTop:6}}>What do you reason about?</Text><Text color="secondary" style={{marginTop:7}}>Pick at least {MIN_INTERESTS} topics. You can change these later.</Text><View style={{marginTop:20}}><Input label="Search topics" value={query} onChangeText={setQuery} placeholder="Music, startups, fitness…" /></View>{categories.isLoading||mine.isLoading?<View style={{gap:12,marginTop:24}}><Skeleton height={42}/><Skeleton height={42}/><Skeleton height={42}/></View>:filtered.map(category=><Section key={category.id} title={category.name}><View style={{flexDirection:"row",flexWrap:"wrap",gap:9}}>{category.interests.map(interest=><Chip key={interest.id} label={interest.name} selected={selected.has(interest.id)} onPress={()=>toggle(interest.id)} />)}</View></Section>)}{error&&<Text variant="caption" color="danger" style={{marginTop:16}}>{error}</Text>}<View style={{marginTop:28,gap:8}}><Text variant="caption" color="secondary">{selected.size} selected{selected.size<MIN_INTERESTS?` (${MIN_INTERESTS} minimum)`:""}</Text><Button label="Continue" disabled={selected.size<MIN_INTERESTS} loading={save.isPending} onPress={()=>void submit()} /></View></Screen>}
