import { memo, useState } from "react";
import { Pressable, StyleSheet, View } from "react-native";
import { Image } from "expo-image";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Avatar, Badge, PressableScale, Text } from "@/components/core";
import type { Post } from "@/features/feed/types";
import { isPlainReshare, isQuote } from "@/features/feed/types";
import { useFollowState } from "@/features/discovery/api";
import { useAuth } from "@/providers/AuthProvider";
import { useTheme } from "@/providers/ThemeProvider";
import { CommentSheet } from "./CommentSheet";
import { PostActions } from "./PostActions";
import { PostMedia } from "./PostMedia";
import { PostText } from "./PostText";
import { ReshareSheet } from "./ReshareSheet";

const relativeTime = (iso: string) => { const minutes = Math.floor((Date.now() - new Date(iso).getTime()) / 60_000); return minutes < 1 ? "just now" : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.floor(minutes / 60)}h ago` : `${Math.floor(minutes / 1440)}d ago`; };

function RepostEmbed({ post, onOpen }: { post: NonNullable<Post["reshared_post"]>; onOpen: () => void }) {
  const { colors } = useTheme(); const preview = post.content.length > 240 ? `${post.content.slice(0, 240)}…` : post.content;
  return <PressableScale onPress={onOpen} style={[styles.embed, { borderColor: colors.border }]}><View style={styles.embedHeader}><Avatar uri={post.author.avatar_url} name={post.author.display_name} size={32} /><View style={{ flex: 1 }}><Text variant="label" numberOfLines={1}>@{post.author.username}</Text><Text variant="caption" color="secondary">{relativeTime(post.created_at)}</Text></View></View>{post.heading ? <Text variant="label" style={{ marginTop: 6 }}>{post.heading}</Text> : null}{preview ? <Text numberOfLines={5} style={{ fontSize: 14, lineHeight: 20, marginTop: 4 }}>{preview}</Text> : null}<PostMedia urls={post.media_urls ?? []} compact /></PressableScale>;
}

export const PostCard = memo(function PostCard({ post }: { post: Post }) {
  const router = useRouter(); const { colors } = useTheme(); const { user } = useAuth(); const relation = useFollowState(post.author.id); const [reshareOpen, setReshareOpen] = useState(false); const [commentsOpen, setCommentsOpen] = useState(false);
  const plain = isPlainReshare(post); const quote = isQuote(post); const original = post.reshared_post; const identity = post.posted_as_page ?? post.author; const name = "name" in identity ? identity.name : identity.display_name; const relationship = user?.id !== post.author.id && !post.posted_as_page && relation.data?.following ? relation.data.followedBy ? "Friends" : "Following" : null; const rendered = plain && original ? original : post;
  const openPost = () => router.push({ pathname: "/posts/[postId]", params: { postId: plain && original ? original.id : post.id } }); const openOriginal = () => original && router.push({ pathname: "/posts/[postId]", params: { postId: original.id } }); const openIdentity = () => "name" in identity ? router.push({ pathname: "/pages/[username]", params: { username: identity.username } }) : router.push({ pathname: "/profiles/[username]", params: { username: identity.username } });
  return <><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.header, { borderBottomColor: colors.border }]}><PressableScale onPress={openIdentity} style={styles.author}><Avatar uri={identity.avatar_url} name={name} size={48} /><View style={styles.details}><View style={styles.nameRow}><Text numberOfLines={1} style={styles.name}>{name}</Text>{identity.is_verified ? <Badge label="✓" /> : null}</View>{post.posted_as_page ? <Text numberOfLines={1} style={[styles.role, { color: colors.textSecondary }]}>@{post.author.username} · posted this</Text> : post.author.roles.length ? <Text numberOfLines={1} style={[styles.role, { color: colors.textSecondary }]}>{post.author.roles.map(role => role.label).join(" · ")}</Text> : null}<View style={styles.time}><Text style={{ fontSize: 12, lineHeight: 18, color: colors.textSecondary }}>{relativeTime(post.created_at)}{post.edited_at ? " · edited" : ""}</Text>{post.visibility === "public" ? <MaterialCommunityIcons name="web" size={11} color={colors.textSecondary} /> : null}</View></View></PressableScale><Image source={require("@/assets/images/splash-logo.png")} style={styles.watermark} contentFit="contain" />{plain || relationship ? <View style={[styles.badges, { backgroundColor: colors.surface }]}>{plain ? <View style={[styles.repostBadge, { backgroundColor: colors.accentSoft }]}><MaterialCommunityIcons name="repeat" size={14} color={colors.accent} /></View> : null}{relationship ? <View style={[styles.relationship, { backgroundColor: colors.surfaceElevated, borderColor: colors.border }]}><Text variant="caption">{relationship}</Text></View> : null}</View> : null}</View>{plain && !original ? <Text color="secondary">This post is no longer available.</Text> : plain && original?.is_archived ? <Text color="secondary">This post has been archived by its author.</Text> : <><Pressable onPress={openPost}><PostText heading={rendered.heading} headingColor={rendered.heading_color} content={rendered.content} /></Pressable><PostMedia urls={rendered.media_urls ?? []} /></>}{quote && original ? <RepostEmbed post={original} onOpen={openOriginal} /> : null}<PostActions postId={post.id} recipientId={post.author.id} recipientName={post.author.display_name} recipientAvatar={post.author.avatar_url} likes={post.like_count} dislikes={post.dislike_count} comments={post.comment_count} shares={post.share_count} support={post.support_count} disagree={post.disagree_count} pushback={post.pushback_count} onComments={() => setCommentsOpen(true)} onReshare={() => setReshareOpen(true)} /></View><ReshareSheet postId={(plain && original ? original : post).id} visible={reshareOpen} onClose={() => setReshareOpen(false)} />{commentsOpen ? <CommentSheet postId={post.id} count={post.comment_count} onClose={() => setCommentsOpen(false)} /> : null}</>;
});

const styles = StyleSheet.create({
  card: { marginHorizontal: 16, padding: 16, gap: 12, borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, shadowColor: "#000", shadowOpacity: 0.16, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 2 }, header: { position: "relative", borderBottomWidth: StyleSheet.hairlineWidth, paddingBottom: 14 }, author: { flexDirection: "row", gap: 12, paddingRight: 42 }, details: { flex: 1, gap: 1 }, nameRow: { flexDirection: "row", alignItems: "center", gap: 6 }, name: { fontSize: 17, lineHeight: 20, fontWeight: "600", flexShrink: 1 }, role: { fontSize: 13, lineHeight: 18 }, time: { flexDirection: "row", alignItems: "center", gap: 4 }, watermark: { position: "absolute", right: 0, top: 1, width: 36, height: 20 }, badges: { position: "absolute", right: 0, bottom: -13, flexDirection: "row", gap: 7, alignItems: "center", paddingLeft: 8, borderRadius: 99 }, repostBadge: { padding: 5, borderRadius: 99 }, relationship: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 99, paddingHorizontal: 8, paddingVertical: 4 }, embed: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 12, padding: 12, overflow: "hidden" }, embedHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
});
