import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Text } from "@/components/core";
import { useCreateComment } from "@/features/feed/api";
import type { Stance } from "@/features/feed/types";
import { useTheme } from "@/providers/ThemeProvider";

const STANCES: Stance[] = ["support", "disagree", "pushback"];
const details: Record<Stance, { label: string; prompt: string; color: string }> = {
  support: { label: "Support", prompt: "Add your reasoning or build on the argument.", color: "#58B981" },
  disagree: { label: "Disagree", prompt: "Explain your position.", color: "#D98978" },
  pushback: { label: "Pushback", prompt: "What would you question, qualify, or add?", color: "#B8862E" },
};

export function StanceComposer({ postId, initial, parentCommentId, onClose }: { postId: string; initial: Stance; parentCommentId?: string; onClose: () => void }) {
  const { colors } = useTheme(); const [stance, setStance] = useState<Stance>(initial); const [content, setContent] = useState(""); const [error, setError] = useState<string | null>(null); const create = useCreateComment(postId); const detail = details[stance];
  const inputRef = useRef<TextInput>(null); const insets = useSafeAreaInsets(); const bottomInset = Platform.OS === "android" ? Math.max(insets.bottom, 34) : insets.bottom;
  useEffect(() => { const timer = setTimeout(() => inputRef.current?.focus(), 250); return () => clearTimeout(timer); }, []);
  const submit = async () => { if (!content.trim() || create.isPending) return; setError(null); try { await create.mutateAsync({ content: content.trim(), stance, ...(parentCommentId ? { parent_comment_id: parentCommentId } : {}) }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Couldn't post this."); } };
  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={s.root}><Pressable style={[s.backdrop, { backgroundColor: colors.overlay }]} onPress={onClose}/><View style={[s.card, { backgroundColor: colors.background, borderTopColor: detail.color, marginBottom: bottomInset }]}><View style={[s.tabs, { borderBottomColor: colors.border }]}>{STANCES.map(value => <Pressable key={value} onPress={() => setStance(value)} style={[s.tab, stance === value && { borderBottomColor: details[value].color, backgroundColor: `${details[value].color}1C` }]}><Text style={[s.tabLabel, { color: stance === value ? details[value].color : colors.textMuted }]}>{details[value].label}</Text></Pressable>)}</View><View style={s.body}><Text color="secondary" style={s.prompt}>{detail.prompt}</Text><View style={s.toolbar}><Text color="muted" style={s.format}>B</Text><Text color="muted" style={[s.format, s.italic]}>I</Text><Text color="muted" style={[s.format, s.strike]}>S</Text><Text color="muted" style={[s.format, s.underline]}>U</Text></View><TextInput ref={inputRef} autoFocus value={content} onChangeText={value => setContent(value.slice(0, 450))} placeholder={detail.prompt} placeholderTextColor={colors.textMuted} selectionColor={detail.color} multiline textAlignVertical="top" maxLength={450} style={[s.input, { color: colors.text, borderColor: detail.color, backgroundColor: colors.surface }]}/>{error&&<Text color="danger" style={s.error}>{error}</Text>}<View style={s.submitRow}><Text color="muted" style={s.counter}>{content.length}/450</Text><Pressable disabled={!content.trim() || create.isPending} onPress={() => void submit()} style={[s.submit, { backgroundColor: detail.color, opacity: !content.trim() || create.isPending ? .5 : 1 }]}>{create.isPending ? <ActivityIndicator size="small" color="#07130D"/> : <Text style={s.submitText}>{detail.label}</Text>}</Pressable></View><Pressable onPress={onClose} style={[s.cancel, { borderColor: colors.border }]}><Text color="secondary" style={s.cancelText}>Cancel</Text></Pressable></View></View></KeyboardAvoidingView></Modal>;
}

const s = StyleSheet.create({ root: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFill }, card: { borderTopWidth: 4, borderTopLeftRadius: 20, borderTopRightRadius: 20, overflow: "hidden" }, tabs: { height: 47, flexDirection: "row", borderBottomWidth: StyleSheet.hairlineWidth }, tab: { flex: 1, alignItems: "center", justifyContent: "center", borderBottomWidth: 2, borderBottomColor: "transparent" }, tabLabel: { fontSize: 14, fontWeight: "700" }, body: { padding: 18 }, prompt: { fontSize: 14, lineHeight: 20, marginBottom: 12 }, toolbar: { height: 24, flexDirection: "row", alignItems: "center", gap: 19, paddingLeft: 8 }, format: { fontSize: 15, fontWeight: "800" }, italic: { fontStyle: "italic", fontWeight: "500" }, strike: { textDecorationLine: "line-through", fontWeight: "500" }, underline: { textDecorationLine: "underline", fontWeight: "500" }, input: { height: 120, borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, paddingTop: 12, fontSize: 15, lineHeight: 21 }, error: { marginTop: 7, fontSize: 12 }, submitRow: { height: 49, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, counter: { fontSize: 12 }, submit: { minWidth: 92, height: 36, borderRadius: 19, alignItems: "center", justifyContent: "center", paddingHorizontal: 17 }, submitText: { color: "#07130D", fontSize: 14, fontWeight: "700" }, cancel: { alignSelf: "center", minWidth: 94, height: 37, borderRadius: 19, borderWidth: 1, alignItems: "center", justifyContent: "center", marginBottom: 3 }, cancelText: { fontSize: 14, fontWeight: "600" } });
