import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/providers/AuthProvider";

export type PageType = "organization" | "brand" | "product";
export type MyPage = { id:string; username:string; name:string; avatar_url:string|null; page_type:PageType; my_role_label:string; my_is_admin:boolean };
export type PageEligibility = { allowed:boolean; overridden:boolean; posts_30d:number; posts_required:number; posts_met:boolean; distinct_engaged_30d:number; distinct_engaged_required:number; distinct_engaged_met:boolean; account_age_days:number; account_age_required:number; account_age_met:boolean };

export function useMyPages(){const{user}=useAuth();return useQuery({queryKey:["my-pages",user?.id],enabled:!!user,queryFn:async():Promise<MyPage[]>=>{const{data,error}=await supabase.from("page_members").select("role_label, is_admin, page:pages(id, username, name, avatar_url, page_type)").eq("user_id",user!.id).eq("status","active");if(error)throw error;return(data??[]).map((row:any)=>{const page=Array.isArray(row.page)?row.page[0]:row.page;return{...page,my_role_label:row.role_label,my_is_admin:row.is_admin}}).filter(page=>page.id)}})}
export function usePageEligibility(){const{user}=useAuth();return useQuery({queryKey:["page-creation-eligibility",user?.id],enabled:!!user,queryFn:async():Promise<PageEligibility>=>{const{data,error}=await supabase.rpc("get_page_creation_eligibility");if(error)throw error;return Array.isArray(data)?data[0]:data}})}
export function useSwitchMode(){const qc=useQueryClient();return useMutation({mutationFn:async(pageId:string|null)=>{const{error}=await supabase.rpc("switch_active_mode",{p_page_id:pageId});if(error)throw error},onSuccess:async()=>{await qc.invalidateQueries({queryKey:["active-identity"]});await qc.invalidateQueries({queryKey:["feed"]})}})}
export function useCreatePage(){const qc=useQueryClient();return useMutation({mutationFn:async(input:{page_type:PageType;name:string;username:string;role_label:string;tagline?:string;bio?:string;topic_ids:string[]})=>{const{topic_ids,...rest}=input;const{data,error}=await supabase.rpc("create_page",{p_page_type:rest.page_type,p_name:rest.name,p_username:rest.username,p_role_label:rest.role_label,p_bio:rest.bio??null,p_tagline:rest.tagline??null,p_avatar_url:null,p_category_id:null,p_parent_organization_id:null});if(error)throw error;if(topic_ids.length){const{error:topicError}=await supabase.from("page_interests").insert(topic_ids.map(interest_id=>({page_id:data.id,interest_id})));if(topicError)throw topicError}return data},onSuccess:()=>void qc.invalidateQueries({queryKey:["my-pages"]})})}
export async function pageUsernameAvailable(username:string){const{data,error}=await supabase.from("pages").select("id").eq("username",username).maybeSingle();if(error)throw error;return!data}
