import { useEffect, useState } from "react";
import { FlatList, Pressable, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useRouter } from "expo-router";
import { Avatar, Button, Chip, Input, Screen, Text } from "@/components/core";
import { ErrorState } from "@/components/feedback";
import { PersonRow } from "@/components/discovery/PersonRow";
import { useSearchPages, useSearchPeople, type Page } from "@/features/discovery/api";
const KEY="ako.recent-searches";type Tab="people"|"pages";
export default function Search(){const router=useRouter();const[input,setInput]=useState("");const[query,setQuery]=useState("");const[tab,setTab]=useState<Tab>("people");const[recent,setRecent]=useState<string[]>([]);useEffect(()=>{void AsyncStorage.getItem(KEY).then(value=>setRecent(value?JSON.parse(value):[])).catch(()=>undefined)},[]);useEffect(()=>{const timer=setTimeout(()=>setQuery(input.trim()),350);return()=>clearTimeout(timer)},[input]);useEffect(()=>{if(query.length<2)return;const timer=setTimeout(()=>setRecent(previous=>{const next=[query,...previous.filter(item=>item!==query)].slice(0,8);void AsyncStorage.setItem(KEY,JSON.stringify(next));return next}),0);return()=>clearTimeout(timer)},[query]);const clear=()=>{setRecent([]);void AsyncStorage.removeItem(KEY)};return <Screen scroll={false}><Button label="Back" variant="ghost" onPress={()=>router.back()}/><Input label="Search AKọ" value={input} onChangeText={setInput} placeholder="Names or usernames" autoCapitalize="none"/><View style={{flexDirection:"row",gap:8,marginVertical:12}}><Chip label="People" selected={tab==="people"} onPress={()=>setTab("people")}/><Chip label="Pages" selected={tab==="pages"} onPress={()=>setTab("pages")}/></View>{query.length<2?<View><View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}}><Text variant="heading">Recent searches</Text>{recent.length>0&&<Button label="Clear" variant="ghost" onPress={clear}/>}</View>{recent.map(item=><Pressable key={item} onPress={()=>setInput(item)}><Text style={{paddingVertical:10}}>{item}</Text></Pressable>)}</View>:tab==="people"?<PeopleResults query={query}/>:<PageResults query={query}/>}</Screen>}
function PeopleResults({query}:{query:string}){const result=useSearchPeople(query);const rows=result.data?.pages.flat()??[];if(result.isError)return <ErrorState message="Search failed." onRetry={()=>void result.refetch()}/>;return <FlatList data={rows} keyExtractor={item=>item.id} renderItem={({item})=><PersonRow person={item}/>} onEndReached={()=>{if(result.hasNextPage&&!result.isFetchingNextPage)void result.fetchNextPage()}} ListEmptyComponent={!result.isLoading?<Text color="secondary" align="center" style={{padding:30}}>No people found.</Text>:null}/>}
function PageResults({query}:{query:string}){const result=useSearchPages(query);const rows=result.data?.pages.flat()??[];if(result.isError)return <ErrorState message="Search failed." onRetry={()=>void result.refetch()}/>;return <FlatList data={rows} keyExtractor={item=>item.id} renderItem={({item})=><PageRow page={item}/>} onEndReached={()=>{if(result.hasNextPage&&!result.isFetchingNextPage)void result.fetchNextPage()}} ListEmptyComponent={!result.isLoading?<Text color="secondary" align="center" style={{padding:30}}>No pages found.</Text>:null}/>}
function PageRow({page}:{page:Page}){const router=useRouter();return <Pressable onPress={()=>router.push({pathname:"/pages/[username]",params:{username:page.username}})} style={{flexDirection:"row",gap:12,alignItems:"center",paddingVertical:12}}><Avatar uri={page.avatar_url} name={page.name}/><View><Text variant="label">{page.name}</Text><Text variant="caption" color="secondary">@{page.username} · {page.page_type}</Text></View></Pressable>}
