import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/providers/AuthProvider";
import { FEED_SELECT, normalizePost } from "@/features/feed/api";
import type { Post } from "@/features/feed/types";

export type Person={id:string;username:string;display_name:string;avatar_url:string|null;bio:string|null;tier:string;follower_count:number;following_count:number;is_private:boolean;is_verified:boolean;hide_followers_list:boolean;hide_following_list:boolean};
export type Page={id:string;username:string;name:string;avatar_url:string|null;tagline:string|null;bio:string|null;page_type:string;follower_count:number;is_verified:boolean};
const PERSON="id, username, display_name, avatar_url, bio, tier, follower_count, following_count, is_private, is_verified, hide_followers_list, hide_following_list";
const PAGE=20;
export function useSuggestedPeople(){const{user}=useAuth();return useQuery({queryKey:["discover-people",user?.id],enabled:!!user,staleTime:300000,queryFn:async()=>{const[{data:follows,error:fError},{data,error}]=await Promise.all([supabase.from("follows").select("following_id").eq("follower_id",user!.id),supabase.from("profiles").select(PERSON).eq("is_deleted",false).neq("id",user!.id).order("follower_count",{ascending:false}).limit(30)]);if(fError)throw fError;if(error)throw error;const followed=new Set((follows??[]).map(x=>x.following_id));return(data as Person[]).filter(x=>!followed.has(x.id)).slice(0,12);}});}
export function useSearchPeople(q:string){return useInfiniteQuery({queryKey:["search-people-mobile",q],enabled:q.trim().length>1,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const safe=q.trim().replace(/[,%()]/g," ");const{data,error}=await supabase.from("profiles").select(PERSON).eq("is_deleted",false).or(`username.ilike.%${safe}%,display_name.ilike.%${safe}%`).range(from,from+PAGE-1);if(error)throw error;return data as Person[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export function useSearchPages(q:string){return useInfiniteQuery({queryKey:["search-pages-mobile",q],enabled:q.trim().length>1,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const safe=q.trim().replace(/[,%()]/g," ");const{data,error}=await supabase.from("pages").select("id, username, name, avatar_url, tagline, bio, page_type, follower_count, is_verified").eq("is_active",true).or(`username.ilike.%${safe}%,name.ilike.%${safe}%`).range(from,from+PAGE-1);if(error)throw error;return data as Page[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export function useProfile(username:string){return useQuery({queryKey:["profile",username],enabled:!!username,queryFn:async()=>{const{data,error}=await supabase.from("profiles").select(PERSON).eq("username",username).single();if(error)throw error;return data as Person;}});}
export function useFollowState(id:string){const{user}=useAuth();return useQuery({queryKey:["follow-state",id,user?.id],enabled:!!user&&!!id,queryFn:async()=>{const[{data:f},{data:r}]=await Promise.all([supabase.from("follows").select("follower_id").eq("follower_id",user!.id).eq("following_id",id).maybeSingle(),supabase.from("follow_requests").select("id").eq("requester_id",user!.id).eq("target_id",id).maybeSingle()]);return{following:!!f,requested:!!r};}});}
export function useToggleFollow(person:Person){const{user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(state:{following:boolean;requested:boolean})=>{if(!user)throw new Error("Not signed in");if(state.following){const{error}=await supabase.from("follows").delete().eq("follower_id",user.id).eq("following_id",person.id);if(error)throw error;}else if(state.requested){const{error}=await supabase.from("follow_requests").delete().eq("requester_id",user.id).eq("target_id",person.id);if(error)throw error;}else if(person.is_private){const{error}=await supabase.from("follow_requests").insert({requester_id:user.id,target_id:person.id});if(error)throw error;}else{const{error}=await supabase.from("follows").insert({follower_id:user.id,following_id:person.id});if(error)throw error;}},onSettled:()=>{void qc.invalidateQueries({queryKey:["follow-state",person.id]});void qc.invalidateQueries({queryKey:["profile",person.username]});}});}
export function usePage(username:string){return useQuery({queryKey:["page",username],enabled:!!username,queryFn:async()=>{const{data,error}=await supabase.from("pages").select("id, username, name, avatar_url, tagline, bio, page_type, follower_count, is_verified").eq("username",username).eq("is_active",true).single();if(error)throw error;return data as Page;}});}
export function usePageFollow(id:string){const{user}=useAuth();return useQuery({queryKey:["page-follow",id,user?.id],enabled:!!user&&!!id,queryFn:async()=>{const{data,error}=await supabase.from("page_follows").select("page_id").eq("follower_id",user!.id).eq("page_id",id).maybeSingle();if(error)throw error;return!!data;}});}
export function useTogglePageFollow(id:string){const{user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(active:boolean)=>{if(!user)throw new Error("Not signed in");const{error}=active?await supabase.from("page_follows").delete().eq("follower_id",user.id).eq("page_id",id):await supabase.from("page_follows").insert({follower_id:user.id,page_id:id});if(error)throw error;},onSettled:()=>{void qc.invalidateQueries({queryKey:["page-follow",id]});void qc.invalidateQueries({queryKey:["page"]});}});}
export function useIdentityPosts(id:string,kind:"profile"|"page"){return useInfiniteQuery({queryKey:["identity-posts",kind,id],enabled:!!id,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;let query=supabase.from("posts").select(FEED_SELECT).eq("is_deleted",false).eq("is_archived",false).order("created_at",{ascending:false}).range(from,from+PAGE-1);query=kind==="profile"?query.eq("author_id",id).is("posted_as_page_id",null):query.eq("posted_as_page_id",id);const{data,error}=await query;if(error)throw error;return(data as unknown as Record<string,unknown>[]).map(normalizePost) as Post[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export function useConnections(id:string,type:"followers"|"following"){return useInfiniteQuery({queryKey:["connections",id,type],enabled:!!id,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const relation=type==="followers"?"follower:profiles!follows_follower_id_fkey":"following:profiles!follows_following_id_fkey";let query=supabase.from("follows").select(`${relation}(${PERSON})`);query=type==="followers"?query.eq("following_id",id):query.eq("follower_id",id);const{data,error}=await query.range(from,from+PAGE-1);if(error)throw error;return(data??[]).map((x:any)=>x[type==="followers"?"follower":"following"] as Person);},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
