import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { cacheProfiles, getCachedProfileByUsername } from "@/lib/local-cache";
import { useAuth } from "@/providers/AuthProvider";
import { FEED_SELECT, normalizePost } from "@/features/feed/api";
import type { Post } from "@/features/feed/types";
import type { Project } from "@/features/projects/api";

export type Person={id:string;username:string;display_name:string;avatar_url:string|null;bio:string|null;website_url?:string|null;tier:string;follower_count:number;following_count:number;is_private:boolean;is_verified:boolean;hide_followers_list:boolean;hide_following_list:boolean;roles?:{position:number;label:string}[]};
export type Page={id:string;username:string;name:string;avatar_url:string|null;tagline:string|null;bio:string|null;page_type:string;follower_count:number;is_verified:boolean};
const PERSON="id, username, display_name, avatar_url, bio, website_url, tier, follower_count, following_count, is_private, is_verified, hide_followers_list, hide_following_list";
const PAGE=20;
export function useSuggestedPeople(){const{user}=useAuth();return useQuery({queryKey:["discover-people",user?.id],enabled:!!user,staleTime:300000,queryFn:async()=>{const[{data:follows,error:fError},{data,error}]=await Promise.all([supabase.from("follows").select("following_id").eq("follower_id",user!.id),supabase.from("profiles").select(PERSON).eq("is_deleted",false).neq("id",user!.id).order("follower_count",{ascending:false}).limit(30)]);if(fError)throw fError;if(error)throw error;const followed=new Set((follows??[]).map(x=>x.following_id));return(data as Person[]).filter(x=>!followed.has(x.id)).slice(0,12);}});}
// "Pages to follow" for the empty Discover state — the most-followed active pages the viewer doesn't already follow (mirrors web's useSuggestedPages).
export function useSuggestedPages(){const{user}=useAuth();return useQuery({queryKey:["discover-pages",user?.id],staleTime:300000,queryFn:async()=>{const[{data:pages,error},{data:follows,error:fError}]=await Promise.all([supabase.from("pages").select("id, username, name, avatar_url, tagline, bio, page_type, follower_count, is_verified").eq("is_active",true).order("follower_count",{ascending:false}).limit(20),user?supabase.from("page_follows").select("page_id").eq("follower_id",user.id):Promise.resolve({data:[] as {page_id:string}[],error:null})]);if(error)throw error;if(fError)throw fError;const followed=new Set((follows??[]).map(x=>x.page_id));return(pages as Page[]).filter(p=>!followed.has(p.id)).slice(0,8);}});}
export function usePageSuggestedPeople(pageId?:string){return useQuery({queryKey:["page-discover-people",pageId],enabled:!!pageId,staleTime:300000,queryFn:async()=>{const[{data:people,error},{data:followers,error:followersError}]=await Promise.all([supabase.from("profiles").select(PERSON).eq("is_deleted",false).order("follower_count",{ascending:false}).limit(30),supabase.from("page_follows").select("follower_id").eq("page_id",pageId!)]);if(error)throw error;if(followersError)throw followersError;const ids=new Set((followers??[]).map(x=>x.follower_id));return(people as Person[]).map(person=>({person,score:ids.has(person.id)?2:0})).sort((a,b)=>b.score-a.score||b.person.follower_count-a.person.follower_count).slice(0,10).map(x=>x.person);}});}
export function useSearchPeople(q:string){return useInfiniteQuery({queryKey:["search-people-mobile",q],enabled:q.trim().length>1,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const safe=q.trim().replace(/[,%()]/g," ");const{data,error}=await supabase.from("profiles").select(PERSON).eq("is_deleted",false).or(`username.ilike.%${safe}%,display_name.ilike.%${safe}%`).range(from,from+PAGE-1);if(error)throw error;return data as Person[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export function useSearchPages(q:string){return useInfiniteQuery({queryKey:["search-pages-mobile",q],enabled:q.trim().length>1,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const safe=q.trim().replace(/[,%()]/g," ");const{data,error}=await supabase.from("pages").select("id, username, name, avatar_url, tagline, bio, page_type, follower_count, is_verified").eq("is_active",true).or(`username.ilike.%${safe}%,name.ilike.%${safe}%`).range(from,from+PAGE-1);if(error)throw error;return data as Page[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export function useSearchPosts(q:string){return useQuery({queryKey:["search-posts-mobile",q],enabled:q.trim().length>1,queryFn:async()=>{const{data,error}=await supabase.from("posts").select(FEED_SELECT).eq("is_deleted",false).eq("is_archived",false).textSearch("search_vector",q.trim(),{type:"websearch"}).limit(20);if(error)throw error;return(data as unknown as Record<string,unknown>[]).map(normalizePost) as Post[];}});}
// Public project search — title or description. Only active, non-private projects: RLS alone would also return private ones (mirrors web's useSearchProjects).
export function useSearchProjects(q:string){return useInfiniteQuery({queryKey:["search-projects-mobile",q],enabled:q.trim().length>1,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const safe=q.trim().replace(/[,%()]/g," ");const{data,error}=await supabase.from("projects").select("*").eq("status","active").eq("is_private",false).or(`title.ilike.%${safe}%,description.ilike.%${safe}%`).order("created_at",{ascending:false}).range(from,from+PAGE-1);if(error)throw error;return data as Project[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export function useProfile(username:string){return useQuery({queryKey:["profile",username],enabled:!!username,queryFn:async()=>{const{data,error}=await supabase.from("profiles").select(`${PERSON}, profile_roles(position, role:roles(label))`).eq("username",username).single();if(error)throw error;const raw=data as any;void cacheProfiles([{id:raw.id,username:raw.username,display_name:raw.display_name,avatar_url:raw.avatar_url}]);return{...raw,roles:(raw.profile_roles??[]).map((row:any)=>({position:row.position,label:(Array.isArray(row.role)?row.role[0]:row.role)?.label??""})).filter((role:{label:string})=>role.label).sort((a:{position:number},b:{position:number})=>a.position-b.position)} as Person;}});}
// Last-known name and avatar for a profile that can't load (offline, never opened on this device),
// from the on-device profiles_cache that chat participants and every profile you open are written
// into. Identity fields only — it backs a stand-in header, never the profile itself. networkMode
// "always" because it's a local SQLite read and has to run precisely when the device is offline.
export function useCachedProfile(username:string,enabled:boolean){return useQuery({queryKey:["cached-profile",username],enabled:enabled&&!!username,networkMode:"always",queryFn:async()=>(await getCachedProfileByUsername(username))??null});}
export function useFollowState(id:string){const{user}=useAuth();return useQuery({queryKey:["follow-state",id,user?.id],enabled:!!user&&!!id,queryFn:async()=>{const[{data:f},{data:r},{data:back}]=await Promise.all([supabase.from("follows").select("follower_id").eq("follower_id",user!.id).eq("following_id",id).maybeSingle(),supabase.from("follow_requests").select("id").eq("requester_id",user!.id).eq("target_id",id).maybeSingle(),supabase.from("follows").select("follower_id").eq("follower_id",id).eq("following_id",user!.id).maybeSingle()]);return{following:!!f,requested:!!r,followedBy:!!back};}});}
export function useToggleFollow(person:Person){const{user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(state:{following:boolean;requested:boolean})=>{if(!user)throw new Error("Not signed in");if(state.following){const{error}=await supabase.from("follows").delete().eq("follower_id",user.id).eq("following_id",person.id);if(error)throw error;}else if(state.requested){const{error}=await supabase.from("follow_requests").delete().eq("requester_id",user.id).eq("target_id",person.id);if(error)throw error;}else if(person.is_private){const{error}=await supabase.from("follow_requests").insert({requester_id:user.id,target_id:person.id});if(error)throw error;}else{const{error}=await supabase.from("follows").insert({follower_id:user.id,following_id:person.id});if(error)throw error;}},onSettled:()=>{void qc.invalidateQueries({queryKey:["follow-state",person.id]});void qc.invalidateQueries({queryKey:["profile",person.username]});}});}
export function usePage(username:string){return useQuery({queryKey:["page",username],enabled:!!username,queryFn:async()=>{const{data,error}=await supabase.from("pages").select("id, username, name, avatar_url, tagline, bio, page_type, follower_count, is_verified").eq("username",username).eq("is_active",true).single();if(error)throw error;return data as Page;}});}
export function usePageFollow(id:string){const{user}=useAuth();return useQuery({queryKey:["page-follow",id,user?.id],enabled:!!user&&!!id,queryFn:async()=>{const{data,error}=await supabase.from("page_follows").select("page_id").eq("follower_id",user!.id).eq("page_id",id).maybeSingle();if(error)throw error;return!!data;}});}
export function useTogglePageFollow(id:string){const{user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(active:boolean)=>{if(!user)throw new Error("Not signed in");const{error}=active?await supabase.from("page_follows").delete().eq("follower_id",user.id).eq("page_id",id):await supabase.from("page_follows").insert({follower_id:user.id,page_id:id});if(error)throw error;},onSettled:()=>{void qc.invalidateQueries({queryKey:["page-follow",id]});void qc.invalidateQueries({queryKey:["page"]});}});}
export function useIdentityPosts(id:string,kind:"profile"|"page"){return useInfiniteQuery({queryKey:["identity-posts",kind,id],enabled:!!id,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;let query=supabase.from("posts").select(FEED_SELECT).eq("is_deleted",false).eq("is_archived",false).order("created_at",{ascending:false}).range(from,from+PAGE-1);query=kind==="profile"?query.eq("author_id",id).is("posted_as_page_id",null):query.eq("posted_as_page_id",id);const{data,error}=await query;if(error)throw error;return(data as unknown as Record<string,unknown>[]).map(normalizePost) as Post[];},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}
export type ProfileMedia={id:string;title:string;description:string|null;thumbnail_url:string|null;created_at:string;price_usd:number;promo_price_usd:number|null;media_details?:{audio_url:string|null;video_url:string|null}|{audio_url:string|null;video_url:string|null}[]|null};
export function useProfileMedia(id:string,enabled=true){return useQuery({queryKey:["profile-media",id],enabled:!!id&&enabled,queryFn:async()=>{const{data,error}=await supabase.from("projects").select("id, title, description, thumbnail_url, created_at, price_usd, promo_price_usd, media_details:project_media_details(audio_url, video_url)").eq("owner_id",id).eq("project_type","media").eq("status","active").eq("is_private",false).order("created_at",{ascending:false});if(error)throw error;return(data??[]) as unknown as ProfileMedia[];}});}
export function useConnections(id:string,type:"followers"|"following"){return useInfiniteQuery({queryKey:["connections",id,type],enabled:!!id,initialPageParam:0,queryFn:async({pageParam})=>{const from=pageParam*PAGE;const relation=type==="followers"?"follower:profiles!follows_follower_id_fkey":"following:profiles!follows_following_id_fkey";let query=supabase.from("follows").select(`${relation}(${PERSON})`);query=type==="followers"?query.eq("following_id",id):query.eq("follower_id",id);const{data,error}=await query.range(from,from+PAGE-1);if(error)throw error;return(data??[]).map((x:any)=>x[type==="followers"?"follower":"following"] as Person);},getNextPageParam:(last,pages)=>last.length===PAGE?pages.length:undefined});}

// Pending requests directed at the signed-in user — what app/requests.tsx
// lists. Query key intentionally matches the local count-only hook already
// living in app/(tabs)/profile.tsx (["incoming-follow-requests", targetId])
// so accepting/declining here also refreshes that badge without it needing
// its own invalidation call.
export type IncomingFollowRequest={id:string;created_at:string;requester:Pick<Person,"id"|"username"|"display_name"|"avatar_url">};
export function useIncomingFollowRequests(){const{user}=useAuth();return useQuery({queryKey:["incoming-follow-requests",user?.id],enabled:!!user,queryFn:async():Promise<IncomingFollowRequest[]>=>{const{data,error}=await supabase.from("follow_requests").select("id, created_at, requester:profiles!follow_requests_requester_id_fkey(id, username, display_name, avatar_url)").eq("target_id",user!.id).order("created_at",{ascending:false});if(error)throw error;return(data??[]) as unknown as IncomingFollowRequest[];}});}
function invalidateAfterRequestResolved(qc:ReturnType<typeof useQueryClient>,requesterId:string,targetId:string){void qc.invalidateQueries({queryKey:["incoming-follow-requests"]});void qc.invalidateQueries({queryKey:["follow-state",targetId]});void qc.invalidateQueries({queryKey:["follow-state",requesterId]});void qc.invalidateQueries({queryKey:["profile"]});void qc.invalidateQueries({queryKey:["connections"]});}
export function useAcceptFollowRequest(){const{user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(request:{id:string;requesterId:string})=>{const{error}=await supabase.rpc("accept_follow_request",{request_id:request.id});if(error)throw error;},onSuccess:(_data,request)=>{if(user)invalidateAfterRequestResolved(qc,request.requesterId,user.id);}});}
export function useDeclineFollowRequest(){const{user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(request:{id:string;requesterId:string})=>{const{error}=await supabase.from("follow_requests").delete().eq("id",request.id);if(error)throw error;},onSuccess:(_data,request)=>{if(user)invalidateAfterRequestResolved(qc,request.requesterId,user.id);}});}
