import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Avatar, Text } from "@/components/core";
import { ErrorState } from "@/components/feedback";
import { PostCard } from "@/components/feed/PostCard";
import { useActiveIdentity } from "@/features/compose/api";
import { type Person, usePageSuggestedPeople, useSearchPeople, useSearchPosts, useSuggestedPeople } from "@/features/discovery/api";
import { usePageNotifications, usePersonalNotifications } from "@/features/notifications/api";
import { useCategories } from "@/features/onboarding/api";
import { useAuth } from "@/providers/AuthProvider";
import { useTheme } from "@/providers/ThemeProvider";

const LOGO_DARK = require("@/assets/images/app-icon-dark-without-tagline.png");
const LOGO_LIGHT = require("@/assets/images/app-icon-light-without-tagline.png");
type SearchTab = "people" | "posts";
function PersonResult({ person }: { person: Person }) { const router = useRouter(); const { colors } = useTheme(); return <Pressable onPress={() => router.push({ pathname: "/profiles/[username]", params: { username: person.username } })} style={({ pressed }) => [s.person, { borderBottomColor: colors.border, opacity: pressed ? .65 : 1 }]}><Avatar uri={person.avatar_url} name={person.display_name} size={40} /><View style={s.personCopy}><Text numberOfLines={1} style={s.personName}>{person.display_name}</Text>{person.bio ? <Text numberOfLines={1} color="secondary" style={s.meta}>{person.bio}</Text> : null}<Text color="muted" style={s.meta}>@{person.username}</Text></View>{person.follower_count > 0 && <Text color="muted" style={s.followers}>{person.follower_count.toLocaleString()} followers</Text>}</Pressable>; }

export default function DiscoverScreen() {
  const { colors, isDark } = useTheme(); const router = useRouter(); const { profile } = useAuth(); const identity = useActiveIdentity();
  const [query, setQuery] = useState(""); const [tab, setTab] = useState<SearchTab>("people"); const [openCategory, setOpenCategory] = useState<string | null>(null);
  const pageId = identity.data?.mode === "page" ? identity.data.page.id : undefined; const personalSuggestions = useSuggestedPeople(); const pageSuggestions = usePageSuggestedPeople(pageId); const suggestions = pageId ? pageSuggestions : personalSuggestions;
  const people = useSearchPeople(query); const posts = useSearchPosts(query); const categories = useCategories(); const personalNotifications = usePersonalNotifications(!pageId); const pageNotifications = usePageNotifications(pageId, !!pageId);
  const notificationRows = pageId ? pageNotifications.data : personalNotifications.data; const unread = notificationRows?.filter((item) => !item.read_at).length ?? 0; const isSearching = query.trim().length > 1;
  const peopleResults = useMemo(() => people.data?.pages.flat() ?? [], [people.data]); const activeSearch = tab === "people" ? people : posts;
  const refreshing = suggestions.isRefetching || categories.isRefetching || (isSearching && activeSearch.isRefetching); const refresh = () => { void suggestions.refetch(); void categories.refetch(); if (isSearching) void activeSearch.refetch(); };
  const identityName = identity.data?.mode === "page" ? identity.data.page.name : profile?.display_name ?? "AKọ"; const identityAvatar = identity.data?.mode === "page" ? identity.data.page.avatar_url : profile?.avatar_url;

  return <SafeAreaView edges={["top", "left", "right"]} style={[s.root, { backgroundColor: colors.background }]}><View style={[s.topHeader, { backgroundColor: colors.surface, borderBottomColor: colors.border }]}><Pressable accessibilityLabel="Open profile" onPress={() => router.push("/(tabs)/profile")}><Avatar uri={identityAvatar} name={identityName} size={34} /></Pressable><Image accessibilityLabel="AKọ" source={isDark ? LOGO_LIGHT : LOGO_DARK} style={s.logo} contentFit="contain" /><Pressable accessibilityLabel="Open notifications" onPress={() => router.push("/(tabs)/notifications")} style={s.bell}><MaterialCommunityIcons name="bell-outline" size={22} color={colors.textSecondary} />{unread > 0 && <View style={[s.badge, { backgroundColor: colors.danger }]}><Text style={s.badgeText}>{unread > 9 ? "9+" : unread}</Text></View>}</Pressable></View>
    <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.accent} />} contentContainerStyle={s.content}>
      <View style={[s.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="magnify" size={19} color={colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search people or posts…" placeholderTextColor={colors.textMuted} selectionColor={colors.accent} autoCapitalize="none" returnKeyType="search" style={[s.input, { color: colors.text }]} />{query.length > 0 && <Pressable accessibilityLabel="Clear search" onPress={() => setQuery("")}><MaterialCommunityIcons name="close" size={19} color={colors.textMuted} /></Pressable>}</View>
      {isSearching ? <SearchResults tab={tab} setTab={setTab} people={people} peopleResults={peopleResults} posts={posts} /> : <><View style={s.section}><Text variant="title" style={s.sectionTitle}>People to follow</Text><Text color="secondary" style={s.sectionSubtitle}>{pageId ? "Based on this page's network and activity." : "Based on your network and activity."}</Text>{suggestions.isLoading ? <Loading label="Loading…" /> : suggestions.isError ? <ErrorState message="Couldn't load suggestions." onRetry={() => void suggestions.refetch()} /> : suggestions.data?.length ? suggestions.data.map((person) => <PersonResult key={person.id} person={person} />) : <Empty label="No suggestions right now." />}</View>
        <View style={s.section}><Text variant="title" style={s.sectionTitle}>Topics</Text><Text color="secondary" style={s.sectionSubtitle}>Explore by what you care about.</Text>{categories.isLoading ? <Loading label="Loading…" /> : categories.isError ? <ErrorState message="Couldn't load topics." onRetry={() => void categories.refetch()} /> : categories.data?.map((category) => { const open = openCategory === category.id; return <View key={category.id} style={{ borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }}><Pressable onPress={() => setOpenCategory(open ? null : category.id)} style={s.category}><Text style={s.categoryName}>{category.name}</Text><MaterialCommunityIcons name={open ? "chevron-up" : "chevron-down"} size={20} color={colors.textMuted} /></Pressable>{open && <View style={s.interests}>{category.interests.map((interest) => <Pressable key={interest.id} onPress={() => router.push({ pathname: "/(tabs)/home", params: { interest: interest.id } })} style={[s.interest, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={s.interestText}>{interest.name}</Text></Pressable>)}</View>}</View>; })}</View></>}
    </ScrollView></SafeAreaView>;
}

function SearchResults({ tab, setTab, people, peopleResults, posts }: { tab: SearchTab; setTab: (tab: SearchTab) => void; people: ReturnType<typeof useSearchPeople>; peopleResults: Person[]; posts: ReturnType<typeof useSearchPosts> }) { const { colors } = useTheme(); return <View><View style={[s.searchTabs, { borderBottomColor: colors.border }]}>{(["people", "posts"] as SearchTab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[s.searchTab, tab === item && { borderBottomColor: colors.accent }]}><Text style={{ color: tab === item ? colors.accent : colors.textMuted, fontWeight: "600", textTransform: "capitalize" }}>{item}</Text></Pressable>)}</View>{tab === "people" ? people.isLoading ? <Loading label="Searching…" /> : people.isError ? <ErrorState message="Search failed." onRetry={() => void people.refetch()} /> : peopleResults.length ? peopleResults.map((person) => <PersonResult key={person.id} person={person} />) : <Empty label="No people found." /> : posts.isLoading ? <Loading label="Searching…" /> : posts.isError ? <ErrorState message="Search failed." onRetry={() => void posts.refetch()} /> : posts.data?.length ? <View style={s.posts}>{posts.data.map((post) => <PostCard key={post.id} post={post} />)}</View> : <Empty label="No posts found." />}</View>; }
function Loading({ label }: { label: string }) { const { colors } = useTheme(); return <View style={s.status}><ActivityIndicator color={colors.accent} /><Text color="muted">{label}</Text></View>; }
function Empty({ label }: { label: string }) { return <Text color="muted" align="center" style={s.empty}>{label}</Text>; }

const s = StyleSheet.create({ root: { flex: 1 }, topHeader: { height: 64, borderBottomWidth: 1, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, logo: { width: 71, height: 36 }, bell: { width: 36, height: 36, alignItems: "center", justifyContent: "center" }, badge: { position: "absolute", right: 0, top: 0, minWidth: 16, height: 16, paddingHorizontal: 4, borderRadius: 8, alignItems: "center", justifyContent: "center" }, badgeText: { color: "white", fontSize: 10, lineHeight: 12, fontWeight: "700" }, content: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 36 }, search: { height: 48, paddingHorizontal: 14, borderRadius: 16, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 24 }, input: { flex: 1, height: 46, padding: 0, fontSize: 14 }, section: { marginBottom: 28 }, sectionTitle: { fontSize: 21, lineHeight: 27 }, sectionSubtitle: { fontSize: 14, lineHeight: 19, marginTop: 2, marginBottom: 12 }, person: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth }, personCopy: { flex: 1, minWidth: 0 }, personName: { fontSize: 14, lineHeight: 19, fontWeight: "700" }, meta: { fontSize: 12, lineHeight: 17 }, followers: { fontSize: 12, lineHeight: 17, flexShrink: 0 }, searchTabs: { flexDirection: "row", gap: 24, borderBottomWidth: 1, marginBottom: 3 }, searchTab: { paddingHorizontal: 2, paddingBottom: 11, borderBottomWidth: 2, borderBottomColor: "transparent" }, posts: { gap: 14, marginHorizontal: -16, paddingTop: 12 }, status: { minHeight: 90, alignItems: "center", justifyContent: "center", gap: 8 }, empty: { paddingVertical: 34 }, category: { minHeight: 54, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, categoryName: { fontSize: 16, lineHeight: 21, fontWeight: "600" }, interests: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingBottom: 16 }, interest: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 }, interestText: { fontSize: 14, lineHeight: 18 } });
