import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Modal, Pressable, RefreshControl, StyleSheet, TextInput, View } from "react-native";
import { Icon, type IconName } from "@/components/core/Icon";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Avatar, Text } from "@/components/core";
import { ErrorState, OfflineState } from "@/components/feedback";
import { getScreenState } from "@/lib/screenState";
import { messagePreview, type ConversationSummary, useConversations, useUpdateConversation } from "@/features/messaging/api";
import { useAuth } from "@/providers/AuthProvider";
import { useTheme } from "@/providers/ThemeProvider";

function ago(value: string) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 1 ? "now" : minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.floor(minutes / 60)}h` : `${Math.floor(minutes / 1440)}d`; }
function identity(row: ConversationSummary) { return row.is_group && row.team_page ? { name: row.team_page.name, avatar: row.team_page.avatar_url } : { name: row.other_participant.display_name, avatar: row.other_participant.avatar_url }; }

export default function InboxScreen() {
  const { colors } = useTheme(); const router = useRouter(); const { user } = useAuth();
  const conversations = useConversations(); const update = useUpdateConversation();
  const [search, setSearch] = useState(""); const [active, setActive] = useState<ConversationSummary | null>(null);
  const [selecting, setSelecting] = useState(false); const [selected, setSelected] = useState<Set<string>>(new Set());
  const rows = useMemo(() => { const q = search.trim().toLowerCase(); return (conversations.data ?? []).filter(row => !q || identity(row).name.toLowerCase().includes(q) || messagePreview(row.last_message?.content ?? "").toLowerCase().includes(q)); }, [conversations.data, search]);
  const close = () => setActive(null); const choose = (id: string) => setSelected(old => { const next = new Set(old); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const exitSelection = () => { setSelecting(false); setSelected(new Set()); };
  const pin = () => { if (active) update.mutate({ id: active.id, pinned_at: active.pinned_at ? null : new Date().toISOString() }); close(); };
  const archiveChat = () => { if (active) update.mutate({ id: active.id, archived_at: new Date().toISOString(), pinned_at: null }); close(); };
  const deleteOne = () => { const row = active; close(); if (row) Alert.alert("Delete chat?", "This removes the conversation from your view.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => update.mutate({ id: row.id, hidden_at: new Date().toISOString() }) }]); };
  const bulkArchive = () => { selected.forEach(id => update.mutate({ id, archived_at: new Date().toISOString(), pinned_at: null })); exitSelection(); };
  const bulkDelete = () => Alert.alert("Delete chats?", "This removes the selected conversations from your view.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { selected.forEach(id => update.mutate({ id, hidden_at: new Date().toISOString() })); exitSelection(); } }]);
  const render = ({ item }: { item: ConversationSummary }) => { const who = identity(item); const mine = item.last_message?.sender_id === user?.id; const voice = !!item.last_message && !item.last_message.is_deleted && messagePreview(item.last_message.content) === "Voice note"; const isSelected = selected.has(item.id); return <Pressable onPress={() => selecting ? choose(item.id) : router.push({ pathname: "/messages/[conversationId]", params: { conversationId: item.id } })} onLongPress={() => setActive(item)} delayLongPress={450} style={({ pressed }) => [s.row, { borderBottomColor: colors.border, opacity: pressed ? .68 : 1 }]}>{selecting && <View style={{ width: 20, height: 20, borderRadius: 10, borderWidth: 1, alignItems: "center", justifyContent: "center", borderColor: isSelected ? colors.accent : colors.border, backgroundColor: isSelected ? colors.accent : "transparent" }}>{isSelected && <View style={{ width: 8, height: 8, borderRadius: 4, backgroundColor: colors.background }} />}</View>}<Avatar uri={who.avatar} name={who.name} size={48} /><View style={s.copy}><View style={s.rowTop}><View style={s.nameWrap}>{item.pinned_at && <Icon name="pin" size={13} color={colors.textMuted} />}<Text numberOfLines={1} style={[s.name, item.unreadCount > 0 && s.unread]}>{who.name}</Text></View><Text color="muted" style={s.time}>{ago(item.last_message_at)}</Text></View><View style={s.previewRow}>{mine && item.last_message && !item.last_message.is_deleted && <Icon name={item.last_message.read_at ? "check-check" : "check"} size={15} color={item.last_message.read_at ? colors.accent : colors.textMuted} />}{voice && <Icon name="mic" size={14} color={colors.textMuted} />}<Text color="muted" numberOfLines={1} style={s.preview}>{item.last_message?.is_deleted ? "This message was deleted" : messagePreview(item.last_message?.content ?? "Say hello")}</Text></View></View></Pressable>; };
  return <SafeAreaView edges={["top", "left", "right"]} style={[s.root, { backgroundColor: colors.background }]}>
    {selecting ? <View style={[s.selectHeader, { borderBottomColor: colors.border }]}><Pressable onPress={exitSelection} style={s.headerIcon}><Icon name="x" size={25} color={colors.textSecondary} /></Pressable><Text style={s.selectedLabel}>{selected.size} selected</Text><Pressable disabled={!selected.size} onPress={bulkArchive} style={s.headerIcon}><Icon name="archive" size={24} color={colors.textSecondary} /></Pressable><Pressable disabled={!selected.size} onPress={bulkDelete} style={s.headerIcon}><Icon name="trash-2" size={24} color={colors.danger} /></Pressable></View> : <><View style={[s.header, { borderBottomColor: colors.border }]}><View style={s.titleRow}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/(tabs)/home")} style={s.headerIcon}><Icon name="arrow-left" size={23} color={colors.textSecondary} /></Pressable><Text style={s.title}>Messages</Text></View><Pressable onPress={() => router.push("/messages/archive")} style={[s.archive, { borderTopColor: colors.border }]}><View style={[s.archiveIcon, { backgroundColor: colors.accentSoft }]}><Icon name="archive" size={19} color={colors.accent} /></View><Text style={s.archiveText}>Archive</Text><Icon name="chevron-right" size={19} color={colors.textMuted} /></Pressable></View>{!!conversations.data?.length && <View style={[s.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Icon name="search" size={19} color={colors.textMuted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search messages..." placeholderTextColor={colors.textMuted} style={[s.input, { color: colors.text }]} /></View>}</>}
    {getScreenState(conversations) === "offline" ? <OfflineState onRetry={() => void conversations.refetch()} /> : conversations.isLoading ? <ActivityIndicator color={colors.accent} style={s.loader} /> : conversations.isError ? <ErrorState message="Couldn't load messages." onRetry={() => void conversations.refetch()} /> : <FlatList data={rows} renderItem={render} keyExtractor={row => row.id} contentContainerStyle={s.list} refreshControl={<RefreshControl refreshing={conversations.isRefetching} onRefresh={() => void conversations.refetch()} tintColor={colors.accent} />} ListEmptyComponent={<Text color="muted" align="center" style={s.empty}>No conversations yet. Message someone from their profile.</Text>} />}
    {!selecting && <Text color="muted" align="center" style={s.hint}>Press and hold a conversation to pin, archive, or delete it.</Text>}
    {active && <Modal visible transparent animationType="fade" onRequestClose={close}><View style={s.modalRoot}><Pressable style={[s.backdrop, { backgroundColor: colors.overlay }]} onPress={close} /><View style={[s.sheet, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text color="muted" numberOfLines={1} style={s.sheetName}>{identity(active).name}</Text><SheetAction icon={active.pinned_at ? "pin-off" : "pin"} label={active.pinned_at ? "Unpin from top" : "Pin to top"} color={colors.text} onPress={pin} /><SheetAction icon="archive" label="Archive" color={colors.text} onPress={archiveChat} /><SheetAction icon="check-square" label="Select chats" color={colors.text} onPress={() => { const id = active.id; close(); setSelecting(true); setSelected(new Set([id])); }} /><SheetAction icon="trash-2" label="Delete chat" color={colors.danger} onPress={deleteOne} /><Pressable onPress={close} style={[s.cancel, { borderTopColor: colors.border }]}><Text color="secondary" style={s.cancelText}>Cancel</Text></Pressable></View></View></Modal>}
  </SafeAreaView>;
}
function SheetAction({ icon, label, color, onPress }: { icon: IconName; label: string; color: string; onPress: () => void }) { return <Pressable onPress={onPress} style={s.sheetAction}><Icon name={icon} size={23} color={color} /><Text style={[s.sheetActionText, { color }]}>{label}</Text></Pressable>; }
const s = StyleSheet.create({ root: { flex: 1 }, header: { borderBottomWidth: StyleSheet.hairlineWidth }, titleRow: { height: 66, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 3 }, headerIcon: { width: 42, height: 44, alignItems: "center", justifyContent: "center" }, title: { fontFamily: "serif", fontSize: 25, lineHeight: 31 }, archive: { height: 64, paddingHorizontal: 16, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 12 }, archiveIcon: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" }, archiveText: { flex: 1, fontSize: 14, fontWeight: "700" }, search: { height: 43, marginHorizontal: 16, marginTop: 12, marginBottom: 3, borderWidth: 1, borderRadius: 22, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8 }, input: { flex: 1, height: 41, padding: 0, fontSize: 14 }, loader: { marginTop: 45 }, list: { paddingHorizontal: 24, paddingTop: 4, paddingBottom: 42, flexGrow: 1 }, row: { minHeight: 86, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 12 }, copy: { flex: 1, minWidth: 0, gap: 3 }, rowTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, nameWrap: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 5 }, name: { fontSize: 16, lineHeight: 21, fontWeight: "700", flexShrink: 1 }, unread: { fontWeight: "800" }, time: { fontSize: 13, marginLeft: 8 }, previewRow: { flexDirection: "row", alignItems: "center", gap: 4 }, preview: { fontSize: 16, lineHeight: 21, flex: 1 }, empty: { paddingTop: 48, fontSize: 14 }, hint: { position: "absolute", left: 24, right: 24, bottom: 5, fontSize: 10, opacity: .55 }, selectHeader: { height: 70, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth }, selectedLabel: { flex: 1, fontSize: 16, fontWeight: "700" }, modalRoot: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFill }, sheet: { borderTopWidth: StyleSheet.hairlineWidth, borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: "hidden", paddingTop: 15 }, sheetName: { paddingHorizontal: 24, paddingBottom: 10, fontSize: 15 }, sheetAction: { height: 67, paddingHorizontal: 25, flexDirection: "row", alignItems: "center", gap: 20 }, sheetActionText: { fontSize: 18, fontWeight: "500" }, cancel: { height: 64, borderTopWidth: StyleSheet.hairlineWidth, marginTop: 2, alignItems: "center", justifyContent: "center" }, cancelText: { fontSize: 18, fontWeight: "500" } });
