import { useCallback, useMemo } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Avatar, Text } from "@/components/core";
import { EmptyState, ErrorState } from "@/components/feedback";
import { useActiveIdentity } from "@/features/compose/api";
import { type AppNotification, useMarkAllNotificationsRead, useMarkNotificationRead, usePageNotifications, usePersonalNotifications } from "@/features/notifications/api";
import { useTheme } from "@/providers/ThemeProvider";

type IconName = keyof typeof MaterialCommunityIcons.glyphMap;
const TYPES: Record<string, { icon: IconName; verb: string }> = {
  like: { icon: "heart", verb: "liked your post" }, dislike: { icon: "thumb-down", verb: "disliked your post" }, support: { icon: "hand-heart", verb: "supported your post" }, disagree: { icon: "thumb-down-outline", verb: "disagreed with your post" }, pushback: { icon: "message-alert-outline", verb: "pushed back on your post" }, reshare: { icon: "repeat", verb: "reshared your post" }, quote: { icon: "format-quote-close", verb: "quoted your post" }, share: { icon: "share-variant", verb: "shared your post" },
  comment_like: { icon: "heart", verb: "liked your comment" }, comment_dislike: { icon: "thumb-down", verb: "disliked your comment" }, comment_reply: { icon: "reply", verb: "replied to your comment" }, post_comment_activity: { icon: "comment-outline", verb: "commented on your post" }, follow: { icon: "account-plus-outline", verb: "followed you" }, follow_request: { icon: "account-clock-outline", verb: "sent you a follow request" }, follow_request_accepted: { icon: "account-check-outline", verb: "accepted your follow request" }, gift_received: { icon: "gift-outline", verb: "sent you a gift" },
  page_role_invite: { icon: "account-group-outline", verb: "invited you to help manage a page" }, page_role_accepted: { icon: "account-check-outline", verb: "accepted your page invitation" }, page_role_declined: { icon: "account-cancel-outline", verb: "declined your page invitation" }, post_tagged: { icon: "tag-outline", verb: "tagged you in a post" }, project_tagged: { icon: "tag-outline", verb: "tagged you in a project" }, collaboration_invite: { icon: "account-multiple-plus-outline", verb: "invited you to collaborate" }, collaboration_accepted: { icon: "account-multiple-check-outline", verb: "accepted your collaboration invitation" }, collaboration_declined: { icon: "account-multiple-remove-outline", verb: "declined your collaboration invitation" }, mention: { icon: "at", verb: "mentioned you" },
  moderation_notice: { icon: "shield-alert-outline", verb: "sent you a moderation notice" }, promotion_approved: { icon: "check-decagram-outline", verb: "approved your promotion" }, promotion_declined: { icon: "alert-circle-outline", verb: "declined your promotion" }, post_published: { icon: "send-check-outline", verb: "Your scheduled post was published" }, room_meeting_scheduled: { icon: "calendar-clock-outline", verb: "scheduled a room meeting" }, project_purchased: { icon: "cart-check", verb: "purchased your project" }, affiliate_commission_earned: { icon: "cash-plus", verb: "You earned an affiliate commission" }, withdrawal_status: { icon: "bank-transfer", verb: "Your withdrawal status changed" }, gig_created_from_collaboration: { icon: "briefcase-check-outline", verb: "A gig was created from your collaboration" }, music_credit_request: { icon: "music-note-plus", verb: "requested a music credit" }, admin_message: { icon: "bell-outline", verb: "sent an announcement" }, system: { icon: "bell-outline", verb: "sent you an update" },
};
const NO_ACTOR = new Set(["system", "admin_message", "moderation_notice", "promotion_approved", "promotion_declined", "post_published", "affiliate_commission_earned", "withdrawal_status", "gig_created_from_collaboration"]);

function timeAgo(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "now"; const minutes = Math.floor(seconds / 60); if (minutes < 60) return `${minutes}m`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h`; const days = Math.floor(hours / 24); if (days < 7) return `${days}d`; return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" }); }

export default function NotificationsScreen() {
  const { colors } = useTheme(); const router = useRouter(); const identity = useActiveIdentity(); const pageId = identity.data?.mode === "page" ? identity.data.page.id : undefined;
  const personal = usePersonalNotifications(!pageId); const page = usePageNotifications(pageId, !!pageId); const query = pageId ? page : personal; const notifications = useMemo(() => query.data ?? [], [query.data]);
  const markRead = useMarkNotificationRead(pageId); const markAll = useMarkAllNotificationsRead(pageId); const unread = useMemo(() => notifications.filter((item) => !item.read_at).length, [notifications]);
  const open = useCallback((item: AppNotification) => { if (!item.read_at) markRead.mutate(item.id); if (item.type === "page_role_invite") { router.push("/pages/index"); return; } if (item.target_type === "post" && item.target_id) { router.push(`/posts/${item.target_id}`); return; } if (item.target_type === "comment" && item.comment_post_id) { router.push(`/posts/${item.comment_post_id}`); return; } if (item.target_type === "profile" && item.actor?.username) { router.push(`/profiles/${item.actor.username}`); return; } if ((item.type === "page_role_accepted" || item.type === "page_role_declined") && item.actor?.username) router.push(`/profiles/${item.actor.username}`); }, [markRead, router]);
  const renderItem = useCallback(({ item }: { item: AppNotification }) => { const config = TYPES[item.type] ?? { icon: "bell-outline" as IconName, verb: item.preview_text || "sent you a notification" }; const showActor = !!item.actor && !NO_ACTOR.has(item.type); const verb = item.target_type === "project" ? config.verb.replace("your post", "your project") : config.verb; return <Pressable onPress={() => open(item)} style={({ pressed }) => [s.row, { borderBottomColor: colors.border, backgroundColor: !item.read_at ? colors.unread : colors.background, opacity: pressed ? .75 : 1 }]}>{showActor ? <Avatar uri={item.actor!.avatar_url} name={item.actor!.display_name} size={34} /> : <View style={[s.iconCircle, { backgroundColor: colors.accentSoft }]}><MaterialCommunityIcons name={config.icon} size={17} color={colors.accent} /></View>}<View style={s.copy}><Text style={s.message}>{showActor && <Text style={s.actor}>{item.actor!.display_name} </Text>}{verb}</Text>{item.preview_text && item.type !== "system" && <Text numberOfLines={1} color="muted" style={s.preview}>“{item.preview_text}”</Text>}<Text color="muted" style={s.time}>{timeAgo(item.created_at)}</Text></View>{!item.read_at && <View style={[s.dot, { backgroundColor: colors.accent }]} />}</Pressable>; }, [colors, open]);
  return <View style={[s.root, { backgroundColor: colors.background }]}><View style={[s.header, { borderBottomColor: colors.border }]}><Text variant="title">{pageId && identity.data?.mode === "page" ? `${identity.data.page.name}'s Notifications` : "Notifications"}</Text><Pressable disabled={!unread || markAll.isPending} onPress={() => markAll.mutate()}><Text color="accent" style={{ opacity: unread ? 1 : .45 }}>{markAll.isPending ? "Marking…" : "Mark all read"}</Text></Pressable></View>{query.isLoading || identity.isLoading ? <ActivityIndicator color={colors.accent} style={s.loader} /> : query.isError ? <ErrorState message="Couldn't load notifications." onRetry={() => void query.refetch()} /> : <FlatList data={notifications} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingHorizontal: 16, flexGrow: notifications.length ? undefined : 1 }} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={colors.accent} />} ListEmptyComponent={<EmptyState icon="bell-outline" title="No notifications yet" message="Your activity will show up here." />} />}</View>;
}
const s = StyleSheet.create({ root: { flex: 1 }, header: { height: 76, paddingTop: 18, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1 }, loader: { flex: 1 }, row: { minHeight: 68, marginHorizontal: -16, paddingHorizontal: 16, paddingVertical: 13, flexDirection: "row", alignItems: "flex-start", gap: 10, borderBottomWidth: StyleSheet.hairlineWidth }, iconCircle: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, minWidth: 0 }, message: { fontSize: 14, lineHeight: 19 }, actor: { fontSize: 14, lineHeight: 19, fontWeight: "700" }, preview: { fontSize: 13, lineHeight: 17, marginTop: 1 }, time: { fontSize: 12, lineHeight: 16, marginTop: 1 }, dot: { width: 8, height: 8, borderRadius: 4, marginTop: 7 } });
