import { useState } from "react";
import { ActivityIndicator, Alert, FlatList, Modal, Pressable, RefreshControl, StyleSheet, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Avatar, Text } from "@/components/core";
import { ErrorState } from "@/components/feedback";
import { messagePreview, type ConversationSummary, useConversations, useUpdateConversation } from "@/features/messaging/api";
import { useTheme } from "@/providers/ThemeProvider";

function ago(value: string) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 1 ? "now" : minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.floor(minutes / 60)}h` : `${Math.floor(minutes / 1440)}d`; }
function chat(row: ConversationSummary) { return row.is_group && row.team_page ? { name: row.team_page.name, avatar: row.team_page.avatar_url } : { name: row.other_participant.display_name, avatar: row.other_participant.avatar_url }; }

export default function ArchiveScreen() {
  const router = useRouter(); const { colors } = useTheme(); const conversations = useConversations(true); const update = useUpdateConversation();
  const [expanded, setExpanded] = useState(false); const [active, setActive] = useState<ConversationSummary | null>(null);
  const close = () => setActive(null); const unarchive = () => { if (active) update.mutate({ id: active.id, archived_at: null }); close(); };
  const deleteChat = () => { const row = active; close(); if (row) Alert.alert("Delete chat?", "This removes the conversation from your view.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => update.mutate({ id: row.id, hidden_at: new Date().toISOString() }) }]); };
  const render = ({ item }: { item: ConversationSummary }) => { const who = chat(item); const voice = !!item.last_message && !item.last_message.is_deleted && messagePreview(item.last_message.content) === "Voice note"; return <Pressable onPress={() => router.push({ pathname: "/messages/[conversationId]", params: { conversationId: item.id } })} onLongPress={() => setActive(item)} delayLongPress={450} style={({ pressed }) => [s.row, { borderBottomColor: colors.border, opacity: pressed ? .68 : 1 }]}><Avatar uri={who.avatar} name={who.name} size={48} /><View style={s.copy}><View style={s.nameLine}><Text numberOfLines={1} style={s.name}>{who.name}</Text><Text color="muted" style={s.time}>{ago(item.last_message_at)}</Text></View><View style={s.previewLine}>{voice && <MaterialCommunityIcons name="microphone" size={14} color={colors.textMuted} />}<Text color="muted" numberOfLines={1} style={s.preview}>{item.last_message?.is_deleted ? "This message was deleted" : messagePreview(item.last_message?.content ?? "Say hello")}</Text></View></View></Pressable>; };
  const data = expanded ? conversations.data ?? [] : [];
  return <SafeAreaView edges={["top", "left", "right"]} style={[s.root, { backgroundColor: colors.background }]}><View style={[s.header, { borderBottomColor: colors.border }]}><Pressable onPress={() => router.back()} style={s.back}><MaterialCommunityIcons name="arrow-left" size={23} color={colors.textSecondary} /></Pressable><Text style={s.title}>Archive</Text></View>{conversations.isLoading ? <ActivityIndicator color={colors.accent} style={s.loader} /> : conversations.isError ? <ErrorState message="Couldn't load archived messages." onRetry={() => void conversations.refetch()} /> : <FlatList data={data} renderItem={render} keyExtractor={item => item.id} contentContainerStyle={[s.list, !data.length && s.emptyList]} refreshControl={<RefreshControl refreshing={conversations.isRefetching} onRefresh={() => void conversations.refetch()} tintColor={colors.accent} />} ListHeaderComponent={<Pressable onPress={() => setExpanded(value => !value)} style={s.section}><Text style={s.sectionTitle}>Archived messages ({conversations.data?.length ?? 0})</Text><MaterialCommunityIcons name={expanded ? "chevron-up" : "chevron-down"} size={23} color={colors.textSecondary} /></Pressable>} ListEmptyComponent={expanded ? <Text color="muted" align="center" style={s.empty}>Archived chats and message requests will appear here.</Text> : null} />}{active && <Modal transparent visible animationType="fade" onRequestClose={close}><View style={s.modalRoot}><Pressable style={[s.backdrop, { backgroundColor: colors.overlay }]} onPress={close} /><View style={[s.sheet, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text color="muted" numberOfLines={1} style={s.sheetName}>{chat(active).name}</Text><Pressable onPress={unarchive} style={s.action}><MaterialCommunityIcons name="archive-arrow-up-outline" size={23} color={colors.text} /><Text style={s.actionText}>Unarchive</Text></Pressable><Pressable onPress={deleteChat} style={s.action}><MaterialCommunityIcons name="trash-can-outline" size={23} color={colors.danger} /><Text color="danger" style={s.actionText}>Delete chat</Text></Pressable><Pressable onPress={close} style={[s.cancel, { borderTopColor: colors.border }]}><Text color="secondary" style={s.cancelText}>Cancel</Text></Pressable></View></View></Modal>}</SafeAreaView>;
}
const s = StyleSheet.create({ root: { flex: 1 }, header: { height: 66, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 3, borderBottomWidth: StyleSheet.hairlineWidth }, back: { width: 42, height: 44, alignItems: "center", justifyContent: "center" }, title: { fontFamily: "serif", fontSize: 25, lineHeight: 31 }, loader: { marginTop: 45 }, list: { paddingHorizontal: 24, paddingBottom: 28, flexGrow: 1 }, emptyList: { flexGrow: 1 }, section: { height: 84, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sectionTitle: { fontFamily: "serif", fontSize: 19 }, row: { minHeight: 86, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 12 }, copy: { flex: 1, minWidth: 0, gap: 3 }, nameLine: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, name: { flex: 1, fontSize: 16, lineHeight: 21, fontWeight: "700" }, time: { fontSize: 13 }, previewLine: { flexDirection: "row", alignItems: "center", gap: 4 }, preview: { flex: 1, fontSize: 16, lineHeight: 21 }, empty: { paddingTop: 34, fontSize: 14 }, modalRoot: { flex: 1, justifyContent: "flex-end" }, backdrop: { ...StyleSheet.absoluteFill }, sheet: { borderTopWidth: StyleSheet.hairlineWidth, borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: "hidden", paddingTop: 15 }, sheetName: { paddingHorizontal: 24, paddingBottom: 10, fontSize: 15 }, action: { height: 67, paddingHorizontal: 25, flexDirection: "row", alignItems: "center", gap: 20 }, actionText: { fontSize: 18, fontWeight: "500" }, cancel: { height: 64, borderTopWidth: StyleSheet.hairlineWidth, marginTop: 2, alignItems: "center", justifyContent: "center" }, cancelText: { fontSize: 18, fontWeight: "500" } });
