// File: components/core/Icon.tsx
//
// The app's one icon component. Web draws every icon with lucide-react
// (1.33.0, see ako/package.json); this is the same glyph set from
// lucide-react-native pinned to the same version, so an icon here is
// the same glyph art web shows in that slot.
//
// Names are lucide's own kebab-case names (`arrow-left`, `trash-2`,
// `more-horizontal`) — the kebab form of the identifier web imports — so a
// web `<Trash2 />` is `<Icon name="trash-2" />` here. Adding an icon means
// adding one import and one registry line below; `IconName` is derived from
// the registry, so a typo'd or unregistered name fails the typecheck.
//
// Why not the icon fonts this replaced (Material Community Icons, Feather):
// fonts can't do what web relies on — a filled active state (`fill`) and a
// per-icon `strokeWidth` (the tab bar's 2 / 1.75) — and MCI's drawing style
// differs from Lucide's, so the same slot rendered differently from web.
//
// Filled states follow web: pass `fill={active ? color : "none"}` (Heart,
// Bookmark, ThumbsDown, Rocket); there is no separate "-outline" glyph.
import type { LucideIcon, LucideProps } from "lucide-react-native";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowDownCircle,
  ArrowLeft,
  ArrowUp,
  ArrowUpCircle,
  AtSign,
  Ban,
  Banknote,
  Bell,
  BellOff,
  Bold,
  BookOpen,
  BookText,
  Bookmark,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarPlus,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Clock3,
  Coins,
  Copy,
  Delete,
  Download,
  Eye,
  EyeOff,
  FileEdit,
  FileText,
  FileUp,
  FileWarning,
  Flag,
  FolderPlus,
  Forward,
  Frown,
  Gift,
  Globe,
  GraduationCap,
  Hand,
  Handshake,
  Heart,
  History,
  ImageIcon,
  Info,
  Italic,
  KeyRound,
  Keyboard,
  LibraryBig,
  Lightbulb,
  Link,
  Link2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  Music,
  Music2,
  Navigation,
  Palette,
  Pause,
  PenSquare,
  Pencil,
  Pin,
  PinOff,
  Play,
  PlayCircle,
  Plus,
  QrCode,
  Quote,
  RefreshCw,
  Receipt,
  Redo2,
  Repeat2,
  Reply,
  Rocket,
  RotateCcw,
  ScanFace,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Strikethrough,
  Sun,
  Tag,
  ThumbsDown,
  Ticket,
  Trash2,
  TrendingUp,
  Underline,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserCircle2,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wallet2,
  WifiOff,
  X,
  XCircle,
} from "lucide-react-native";
import { useTheme } from "@/providers/ThemeProvider";

export const ICONS = {
  "activity": Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "archive": Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-up-circle": ArrowUpCircle,
  "at-sign": AtSign,
  "ban": Ban,
  "banknote": Banknote,
  "bell": Bell,
  "bell-off": BellOff,
  "bold": Bold,
  "book-open": BookOpen,
  "book-text": BookText,
  "bookmark": Bookmark,
  "briefcase": Briefcase,
  "building-2": Building2,
  "calendar-clock": CalendarClock,
  "calendar-plus": CalendarPlus,
  "camera": Camera,
  "check": Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "clock": Clock,
  "clock-3": Clock3,
  "coins": Coins,
  "copy": Copy,
  "delete": Delete,
  "download": Download,
  "eye": Eye,
  "eye-off": EyeOff,
  "file-edit": FileEdit,
  "file-text": FileText,
  "file-up": FileUp,
  "file-warning": FileWarning,
  "flag": Flag,
  "folder-plus": FolderPlus,
  "forward": Forward,
  "frown": Frown,
  "gift": Gift,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "hand": Hand,
  "handshake": Handshake,
  "heart": Heart,
  "history": History,
  "image": ImageIcon,
  "info": Info,
  "italic": Italic,
  "key-round": KeyRound,
  "keyboard": Keyboard,
  "library-big": LibraryBig,
  "lightbulb": Lightbulb,
  "link": Link,
  "link-2": Link2,
  "lock": Lock,
  "log-out": LogOut,
  "mail": Mail,
  "map-pin": MapPin,
  "megaphone": Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "mic": Mic,
  "monitor-smartphone": MonitorSmartphone,
  "moon": Moon,
  "more-horizontal": MoreHorizontal,
  "music": Music,
  "music-2": Music2,
  "navigation": Navigation,
  "palette": Palette,
  "pause": Pause,
  "pen-square": PenSquare,
  "pencil": Pencil,
  "pin": Pin,
  "pin-off": PinOff,
  "play": Play,
  "play-circle": PlayCircle,
  "plus": Plus,
  "qr-code": QrCode,
  "quote": Quote,
  "receipt": Receipt,
  "refresh-cw": RefreshCw,
  "redo-2": Redo2,
  "repeat-2": Repeat2,
  "reply": Reply,
  "rocket": Rocket,
  "rotate-ccw": RotateCcw,
  "scan-face": ScanFace,
  "search": Search,
  "send": Send,
  "settings": Settings,
  "share-2": Share2,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  "smile": Smile,
  "sparkles": Sparkles,
  "sprout": Sprout,
  "star": Star,
  "strikethrough": Strikethrough,
  "sun": Sun,
  "tag": Tag,
  "thumbs-down": ThumbsDown,
  "ticket": Ticket,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  "underline": Underline,
  "undo-2": Undo2,
  "upload": Upload,
  "user": User,
  "user-check": UserCheck,
  "user-circle-2": UserCircle2,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-x": UserX,
  "users": Users,
  "video": Video,
  "volume-1": Volume1,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "wallet": Wallet,
  "wallet-2": Wallet2,
  "wifi-off": WifiOff,
  "x": X,
  "x-circle": XCircle,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
export type IconProps = Omit<LucideProps, "ref"> & { name: IconName };

/** lucide's defaults (24px, stroke 2), with the theme's text colour when no `color` is given. */
export function Icon({ name, size = 24, strokeWidth = 2, color, ...rest }: IconProps) {
  const { colors } = useTheme();
  const Glyph: LucideIcon | undefined = ICONS[name];
  // The type makes an unregistered name a compile error; this only guards a name that arrives untyped
  // (e.g. from server data) so one bad string can't take a whole screen down.
  if (!Glyph) {
    if (__DEV__) console.warn(`Icon: "${name}" is not in the registry (components/core/Icon.tsx).`);
    return null;
  }
  return <Glyph size={size} strokeWidth={strokeWidth} color={color ?? colors.text} {...rest} />;
}
