import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, View } from "react-native";
import Animated, { SlideInDown, useReducedMotion } from "react-native-reanimated";
import { SafeAreaView } from "react-native-safe-area-context";
import { Divider, IconButton, Text } from "@/components/core";
import { useTheme } from "@/providers/ThemeProvider";

const futureActions = [{ icon: "post-outline", label: "Post" }, { icon: "briefcase-outline", label: "Project" }, { icon: "calendar-outline", label: "Event" }, { icon: "video-outline", label: "Meeting" }] as const;
export default function CreateModal() { const router = useRouter(); const { colors, radii } = useTheme(); const reduced = useReducedMotion(); return <View style={[styles.root, { backgroundColor: colors.overlay }]}><Pressable accessibilityLabel="Close create menu" style={StyleSheet.absoluteFill} onPress={() => router.back()} /><Animated.View entering={reduced ? undefined : SlideInDown.duration(240)} style={[styles.sheet, { backgroundColor: colors.surface, borderColor: colors.border, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl }]}><SafeAreaView edges={["bottom"]}><View style={styles.header}><View style={{ flex: 1, gap: 3 }}><Text variant="title">Create on AKọ</Text><Text variant="caption" color="secondary">Creation tools will unlock in their feature phases.</Text></View><IconButton icon="close" label="Close" onPress={() => router.back()} /></View><Divider />{futureActions.map((action) => <View key={action.label} accessibilityState={{ disabled: true }} style={[styles.row, { opacity: 0.48 }]}><View style={[styles.icon, { backgroundColor: colors.accentSoft }]}><MaterialCommunityIcons name={action.icon} size={22} color={colors.accent} /></View><Text variant="label" style={{ flex: 1 }}>{action.label}</Text><Text variant="caption" color="muted">Coming later</Text></View>)}</SafeAreaView></Animated.View></View>; }
const styles = StyleSheet.create({ root: { flex: 1, justifyContent: "flex-end" }, sheet: { borderWidth: 1, paddingHorizontal: 20, paddingTop: 10 }, header: { flexDirection: "row", gap: 16, alignItems: "center", paddingVertical: 14 }, row: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12 }, icon: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center" } });
