import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { Icon } from "@/components/core/Icon";
import { type Href, useRouter } from "expo-router";
import { Text } from "@/components/core";
import { useDraftPosts } from "@/features/activity/api";
import { useTheme } from "@/providers/ThemeProvider";

const rows = [{ key: "saved", icon: "bookmark", label: "Saved", description: "Posts and projects you've bookmarked" }, { key: "liked", icon: "heart", label: "Liked", description: "Posts and projects you've liked" }, { key: "drafts", icon: "file-edit", label: "Drafts", description: "Posts you started but haven't shared yet", count: "draft" }, { key: "scheduled", icon: "send", label: "Scheduled", description: "Posts queued to publish automatically", count: "scheduled" }, { key: "history", icon: "history", label: "History", description: "Posts and projects you've viewed" }, { key: "events", icon: "calendar-clock", label: "Events & meetings", description: "Tickets, meetings, and rooms you're part of" }, { key: "affiliates", icon: "trending-up", label: "Affiliates", description: "Projects you've forked to earn a commission on" }] as const;
export default function Activity() { const router = useRouter(); const { colors } = useTheme(); const drafts = useDraftPosts("draft"); const scheduled = useDraftPosts("scheduled"); return <View style={[s.root, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={s.content}><View style={s.header}><Pressable accessibilityLabel="Back" onPress={() => router.back()} style={s.back}><Icon name="arrow-left" size={22} color={colors.textSecondary}/></Pressable><Text style={s.title}>Activity</Text></View><View style={s.rows}>{rows.map(row => { const countKind = "count" in row ? row.count : undefined; const count = countKind === "draft" ? drafts.data?.length ?? 0 : countKind === "scheduled" ? scheduled.data?.length ?? 0 : 0; return <Pressable key={row.key} onPress={() => router.push({ pathname: "/activity/[kind]", params: { kind: row.key } } as Href)} style={({ pressed }) => [s.row, { borderBottomColor: colors.border, opacity: pressed ? .7 : 1 }]}><View style={[s.chip, { backgroundColor: colors.accentSoft }]}><Icon name={row.icon} size={18} color={colors.accent}/></View><View style={s.copy}><View style={s.labelRow}><Text style={s.label}>{row.label}</Text>{count > 0 ? <View style={[s.count, { backgroundColor: colors.accent }]}><Text style={s.countText}>{count}</Text></View> : null}</View><Text color="secondary" numberOfLines={1} style={s.description}>{row.description}</Text></View><Icon name="chevron-right" size={18} color={colors.textMuted}/></Pressable>; })}</View></ScrollView></View>; }
const s = StyleSheet.create({ root: { flex: 1 }, content: { paddingBottom: 110 }, header: { paddingHorizontal: 16, paddingTop: 24, paddingBottom: 12, flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 32, height: 32, alignItems: "center", justifyContent: "center" }, title: { fontFamily: "serif", fontSize: 24, lineHeight: 30 }, rows: { paddingHorizontal: 16, paddingTop: 8 }, row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth }, chip: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, minWidth: 0 }, labelRow: { flexDirection: "row", alignItems: "center", gap: 7 }, label: { fontSize: 14, lineHeight: 19, fontWeight: "500" }, description: { fontSize: 12, lineHeight: 17 }, count: { minWidth: 18, height: 18, paddingHorizontal: 4, borderRadius: 9, alignItems: "center", justifyContent: "center" }, countText: { color: "#0C0C0B", fontSize: 10, fontWeight: "600" } });
