import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useAudioPlayer, useAudioPlayerStatus } from "expo-audio";
import { Text } from "@/components/core";
import { formatVoiceDuration } from "@/features/messaging/api";
import { supabase } from "@/lib/supabase";
import { useTheme } from "@/providers/ThemeProvider";

export function VoiceNote({path,durationSec,own,viewOnce}:{path:string;durationSec:number;own:boolean;viewOnce?:boolean}){const{colors}=useTheme();const[url,setUrl]=useState<string|null>(null);const[failed,setFailed]=useState(false);const player=useAudioPlayer(url,{updateInterval:250});const status=useAudioPlayerStatus(player);const[spent,setSpent]=useState(false);useEffect(()=>{let alive=true;supabase.storage.from("audio").createSignedUrl(path,3600).then(({data,error})=>{if(!alive)return;if(error||!data?.signedUrl){setFailed(true);return;}setUrl(data.signedUrl);});return()=>{alive=false;};},[path]);useEffect(()=>{if(viewOnce&&!own&&status.didJustFinish)setTimeout(()=>setSpent(true),0);},[own,status.didJustFinish,viewOnce]);const progress=status.duration>0?status.currentTime/status.duration:0;const toggle=async()=>{if(!url)return;if(status.playing){player.pause();return;}const finished=status.didJustFinish||(status.duration>0&&status.currentTime>=status.duration-.05);try{if(finished)await player.seekTo(0);player.play();}catch{setFailed(true);}};if(viewOnce&&spent&&!own)return <View style={s.spent}><MaterialCommunityIcons name="eye-off-outline" size={16} color={colors.textMuted}/><Text color="muted" style={s.spentText}>Opened</Text></View>;return <View style={s.root}><Pressable onPress={()=>void toggle()} style={[s.play,{backgroundColor:own?"#fff":colors.accent}]}>{!url?<ActivityIndicator size="small" color={colors.accent}/>:<MaterialCommunityIcons name={status.playing?"pause":"play"} size={18} color={own?colors.accent:"#07130D"}/>}</Pressable><View style={s.wave}><View style={[s.waveFill,{backgroundColor:own?"rgba(255,255,255,.92)":colors.accent,width:`${Math.max(3,progress*100)}%`}]} />{Array.from({length:30},(_,i)=><View key={i} style={[s.bar,{height:7+(i*7%19),backgroundColor:own?"rgba(255,255,255,.34)":"rgba(140,150,145,.3)"}]}/>)}</View><View style={s.info}>{viewOnce&&<View style={[s.once,{backgroundColor:own?"rgba(255,255,255,.2)":colors.accentSoft}]}><Text style={[s.onceText,{color:own?"#fff":colors.accent}]}>1</Text></View>}<Text style={[s.duration,{color:own?"rgba(255,255,255,.82)":colors.textMuted}]}>{formatVoiceDuration(status.playing||status.currentTime>0?status.currentTime:durationSec)}</Text>{failed&&<Text color="muted" style={s.fail}>Unavailable</Text>}</View></View>}
const s=StyleSheet.create({root:{minWidth:210,flexDirection:"row",alignItems:"center",gap:8,paddingVertical:2},play:{width:35,height:35,borderRadius:18,alignItems:"center",justifyContent:"center"},wave:{height:33,flex:1,overflow:"hidden",flexDirection:"row",alignItems:"center",gap:2,position:"relative"},waveFill:{position:"absolute",left:0,top:0,bottom:0,opacity:.25},bar:{width:2,borderRadius:2},info:{alignItems:"flex-end",gap:2},duration:{fontSize:10,fontVariant:["tabular-nums"]},once:{width:14,height:14,borderRadius:7,alignItems:"center",justifyContent:"center"},onceText:{fontSize:9,fontWeight:"800"},spent:{flexDirection:"row",alignItems:"center",gap:6,paddingVertical:4},spentText:{fontStyle:"italic",fontSize:14},fail:{fontSize:9}});
