import { ActivityIndicator, FlatList, Pressable, StyleSheet, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Text } from "@/components/core";
import { ErrorState } from "@/components/feedback";
import { useHiddenMessages, useUnhideMessage } from "@/features/messaging/api";
import { useAuth } from "@/providers/AuthProvider";
import { useTheme } from "@/providers/ThemeProvider";

function formatTime(value:string){return new Date(value).toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}
export default function HiddenMessagesScreen(){const router=useRouter();const{conversationId}=useLocalSearchParams<{conversationId:string}>();const{colors}=useTheme();const{user}=useAuth();const hidden=useHiddenMessages(conversationId??"");const restore=useUnhideMessage(conversationId??"");return <SafeAreaView edges={["top","left","right"]} style={[s.root,{backgroundColor:colors.background}]}><View style={[s.header,{borderBottomColor:colors.border}]}><Pressable onPress={()=>router.back()} style={s.back}><MaterialCommunityIcons name="arrow-left" size={23} color={colors.textSecondary}/></Pressable><Text style={s.title}>Hidden messages</Text></View>{hidden.isLoading?<ActivityIndicator color={colors.accent} style={s.loading}/>:hidden.isError?<ErrorState message="Couldn't load hidden messages." onRetry={()=>void hidden.refetch()}/>:<FlatList data={hidden.data??[]} keyExtractor={item=>item.id} contentContainerStyle={[s.list,!(hidden.data?.length)&&s.emptyList]} ListEmptyComponent={<Text color="muted" align="center" style={s.empty}>Nothing hidden here. Messages you hide from a chat show up in this list, only for you.</Text>} renderItem={({item})=><View style={[s.row,{borderBottomColor:colors.border}]}><View style={s.copy}><Text color="muted" style={s.meta}>{item.sender_id===user?.id?"You":"Them"} · {formatTime(item.created_at)}</Text><Text numberOfLines={1} style={[s.message,item.is_deleted&&s.deleted]}>{item.is_deleted?"This message was deleted":item.content}</Text></View><Pressable disabled={restore.isPending} onPress={()=>restore.mutate(item.id)} style={s.restore}><MaterialCommunityIcons name="undo-variant" size={15} color={colors.accent}/><Text color="accent" style={s.restoreText}>Restore</Text></Pressable></View>}/>}</SafeAreaView>}
const s=StyleSheet.create({root:{flex:1},header:{height:66,paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:4,borderBottomWidth:StyleSheet.hairlineWidth},back:{height:42,width:38,alignItems:"center",justifyContent:"center"},title:{fontFamily:"serif",fontSize:24,lineHeight:30},loading:{marginTop:54},list:{paddingHorizontal:16},emptyList:{flexGrow:1},empty:{paddingVertical:64,paddingHorizontal:26,fontSize:14,lineHeight:20},row:{minHeight:68,paddingVertical:12,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:"row",alignItems:"center",gap:12},copy:{flex:1,minWidth:0,gap:3},meta:{fontSize:11,lineHeight:15},message:{fontSize:14,lineHeight:19},deleted:{fontStyle:"italic",opacity:.7},restore:{paddingVertical:7,flexDirection:"row",alignItems:"center",gap:5},restoreText:{fontSize:12,fontWeight:"700"}});
